<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BahanKajianSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bahan_kajian')->insert([
            // Teknik Sipil (id_ps = 1)
            ['id_bk' => 1, 'id_ps' => 1, 'nama_kode_bk'=>'BK-1', 'nama_bk_id' => 'Rekayasa Struktur', 'nama_bk_en' => 'Structural Engineering', 'kategori' => 'Inti', 'desc_bk_id' => 'Analisis dan perancangan struktur bangunan tahan gempa.', 'desc_bk_en' => 'Analysis and design of earthquake-resistant building structures.'],
            ['id_bk' => 2, 'id_ps' => 1, 'nama_kode_bk'=>'BK-2', 'nama_bk_id' => 'Rekayasa Geoteknik', 'nama_bk_en' => 'Geotechnical Engineering', 'kategori' => 'Inti', 'desc_bk_id' => 'Studi tentang mekanika tanah dan perancangan pondasi.', 'desc_bk_en' => 'Study of soil mechanics and foundation design.'],
            ['id_bk' => 3, 'id_ps' => 1, 'nama_kode_bk'=>'BK-3', 'nama_bk_id' => 'Manajemen Konstruksi', 'nama_bk_en' => 'Construction Management', 'kategori' => 'Inti', 'desc_bk_id' => 'Perencanaan, penjadwalan, dan pengendalian proyek konstruksi.', 'desc_bk_en' => 'Planning, scheduling, and controlling construction projects.'],

            // Teknik Pertambangan (id_ps = 2)
            ['id_bk' => 4, 'id_ps' => 2, 'nama_kode_bk'=>'BK-1', 'nama_bk_id' => 'Eksplorasi dan Geologi Tambang', 'nama_bk_en' => 'Exploration and Mining Geology', 'kategori' => 'Inti', 'desc_bk_id' => 'Metode pencarian dan evaluasi deposit bahan galian.', 'desc_bk_en' => 'Methods for searching and evaluating mineral deposits.'],
            ['id_bk' => 5, 'id_ps' => 2, 'nama_kode_bk'=>'BK-2', 'nama_bk_id' => 'Teknik Penambangan', 'nama_bk_en' => 'Mining Engineering', 'kategori' => 'Inti', 'desc_bk_id' => 'Studi tentang metode penambangan terbuka dan bawah tanah.', 'desc_bk_en' => 'Study of surface and underground mining methods.'],
            ['id_bk' => 6, 'id_ps' => 2, 'nama_kode_bk'=>'BK-3', 'nama_bk_id' => 'Pengolahan Bahan Galian', 'nama_bk_en' => 'Mineral Processing', 'kategori' => 'Inti', 'desc_bk_id' => 'Proses pemisahan mineral berharga dari bijih.', 'desc_bk_en' => 'The process of separating valuable minerals from ore.'],

            // Teknik Mesin (id_ps = 3)
            ['id_bk' => 7, 'id_ps' => 3, 'nama_kode_bk'=>'BK-1', 'nama_bk_id' => 'Konstruksi dan Perancangan Mesin', 'nama_bk_en' => 'Machine Construction and Design', 'kategori' => 'Inti', 'desc_bk_id' => 'Desain dan analisis komponen dan sistem mekanik.', 'desc_bk_en' => 'Design and analysis of mechanical components and systems.'],
            ['id_bk' => 8, 'id_ps' => 3, 'nama_kode_bk'=>'BK-2', 'nama_bk_id' => 'Konversi Energi', 'nama_bk_en' => 'Energy Conversion', 'kategori' => 'Inti', 'desc_bk_id' => 'Studi tentang mesin termal dan sistem energi terbarukan.', 'desc_bk_en' => 'Study of thermal engines and renewable energy systems.'],
            ['id_bk' => 9, 'id_ps' => 3, 'nama_kode_bk'=>'BK-3', 'nama_bk_id' => 'Ilmu Material dan Manufaktur', 'nama_bk_en' => 'Materials Science and Manufacturing', 'kategori' => 'Inti', 'desc_bk_id' => 'Proses produksi dan sistem manufaktur modern.', 'desc_bk_en' => 'Production processes and modern manufacturing systems.'],

            // Teknik Lingkungan (id_ps = 4)
            ['id_bk' => 10, 'id_ps' => 4, 'nama_kode_bk'=>'BK-1', 'nama_bk_id' => 'Pengendalian Pencemaran', 'nama_bk_en' => 'Pollution Control', 'kategori' => 'Inti', 'desc_bk_id' => 'Teknologi untuk mengendalikan pencemaran air, udara, dan tanah.', 'desc_bk_en' => 'Technologies for controlling water, air, and soil pollution.'],
            ['id_bk' => 11, 'id_ps' => 4, 'nama_kode_bk'=>'BK-2', 'nama_bk_id' => 'Rekayasa Sumber Daya Air', 'nama_bk_en' => 'Water Resources Engineering', 'kategori' => 'Inti', 'desc_bk_id' => 'Pengelolaan dan rekayasa sistem sumber daya air.', 'desc_bk_en' => 'Management and engineering of water resource systems.'],
            ['id_bk' => 12, 'id_ps' => 4, 'nama_kode_bk'=>'BK-3', 'nama_bk_id' => 'Kesehatan dan Keselamatan Lingkungan', 'nama_bk_en' => 'Environmental Health and Safety', 'kategori' => 'Inti', 'desc_bk_id' => 'Analisis risiko dan manajemen kesehatan lingkungan kerja.', 'desc_bk_en' => 'Risk analysis and occupational environmental health management.'],

            // Arsitektur (id_ps = 5)
            ['id_bk' => 13, 'id_ps' => 5, 'nama_kode_bk'=>'BK-1', 'nama_bk_id' => 'Perancangan Arsitektur', 'nama_bk_en' => 'Architectural Design', 'kategori' => 'Inti', 'desc_bk_id' => 'Proses desain kreatif bangunan dan lingkungan binaan.', 'desc_bk_en' => 'The creative design process for buildings and the built environment.'],
            ['id_bk' => 14, 'id_ps' => 5, 'nama_kode_bk'=>'BK-2', 'nama_bk_id' => 'Struktur dan Teknologi Bangunan', 'nama_bk_en' => 'Building Structure and Technology', 'kategori' => 'Inti', 'desc_bk_id' => 'Studi tentang sistem struktur dan teknologi konstruksi bangunan.', 'desc_bk_en' => 'Study of structural systems and building construction technology.'],
            ['id_bk' => 15, 'id_ps' => 5, 'nama_kode_bk'=>'BK-3', 'nama_bk_id' => 'Teori dan Sejarah Arsitektur', 'nama_bk_en' => 'Architectural Theory and History', 'kategori' => 'Inti', 'desc_bk_id' => 'Kajian teoritis dan sejarah perkembangan arsitektur.', 'desc_bk_en' => 'Theoretical study and history of architectural development.'],

            // Teknik Kimia (id_ps = 6)
            ['id_bk' => 16, 'id_ps' => 6, 'nama_kode_bk'=>'BK-1', 'nama_bk_id' => 'Operasi Teknik Kimia', 'nama_bk_en' => 'Chemical Engineering Operations', 'kategori' => 'Inti', 'desc_bk_id' => 'Studi tentang unit operasi dalam industri proses kimia.', 'desc_bk_en' => 'Study of unit operations in the chemical process industry.'],
            ['id_bk' => 17, 'id_ps' => 6, 'nama_kode_bk'=>'BK-2', 'nama_bk_id' => 'Termodinamika Teknik Kimia', 'nama_bk_en' => 'Chemical Engineering Thermodynamics', 'kategori' => 'Inti', 'desc_bk_id' => 'Aplikasi prinsip termodinamika dalam sistem kimia.', 'desc_bk_en' => 'Application of thermodynamic principles in chemical systems.'],
            ['id_bk' => 18, 'id_ps' => 6, 'nama_kode_bk'=>'BK-3', 'nama_bk_id' => 'Rekayasa Reaktor Kimia', 'nama_bk_en' => 'Chemical Reactor Engineering', 'kategori' => 'Inti', 'desc_bk_id' => 'Perancangan dan analisis reaktor kimia.', 'desc_bk_en' => 'Design and analysis of chemical reactors.'],

            // Teknologi Informasi (id_ps = 7)
            ['id_bk' => 19, 'id_ps' => 7, 'nama_kode_bk'=>'BK-1', 'nama_bk_id' => 'Layanan Sistem Virtual', 'nama_bk_en' => 'Virtual Systems and Services', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini membahas tentang virtualisasi server yang meliputi optimalisasi penyimpanan, penerapan klasterisasi sistem operasi secara virtualisasi, serta manajemen jaringan komputer untuk kebutuhan virtualisasi server.', 'desc_bk_en' => 'This course material discusses server virtualization which includes storage optimization, virtual implementation of operating system clustering, and computer network management for server virtualization needs.'],
            ['id_bk' => 20, 'id_ps' => 7, 'nama_kode_bk'=>'BK-2', 'nama_bk_id' => 'Internet of Things', 'nama_bk_en' => 'Internet of Things', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini mencakup pengetahuan dan keterampilan dasar untuk terlibat dalam desain inovatif dan pengembangan solusi IoT, tren dan karakteristik di bidang IoT, analisis tantangan dan pola aplikasi untuk interaksi pengguna dalam pengaturan IoT. Membahas juga efek IoT untuk pemrosesan sinyal, akuisisi data, dan jaringan sensor nirkabel, hubungan antara IoT dan pemrosesan informasi cerdas, dan perbandingan operasi internet dengan operasi IoT.', 'desc_bk_en' => 'This course material covers the basic knowledge and skills to engage in innovative design and development of IoT solutions, trends and characteristics in the IoT field, analysis of challenges and application patterns for user interaction in IoT settings. It also discusses the effects of IoT on signal processing, data acquisition, and wireless sensor networks, the relationship between IoT and intelligent information processing, and a comparison of internet operations with IoT operations.'],
            ['id_bk' => 21, 'id_ps' => 7, 'nama_kode_bk'=>'BK-3', 'nama_bk_id' => 'Jaringan Komputer', 'nama_bk_en' => 'Computer Networks', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini meliputi model rancangan infrastruktur jaringan komputer berbagai model, komunikasi antar interface pada protokol jaringan komputer, routing pada jaringan komputer, model server berbasis VPS untuk keamanan pengelolaan teknologi jaringan, analisis model unjuk kerja kualitas jaringan komputer.', 'desc_bk_en' => 'This course material covers various models of computer network infrastructure design, communication between interfaces in computer network protocols, routing on computer networks, VPS-based server models for managing network technology security, and analysis of computer network quality performance models.'],
            ['id_bk' => 22, 'id_ps' => 7, 'nama_kode_bk'=>'BK-4', 'nama_bk_id' => 'Teknologi Sistem Terintegrasi', 'nama_bk_en' => 'Integrated Systems Technology', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini membahas tentang beberapa topik terkait dengan pemrograman aplikasi, yaitu bahasa skrip, penggunaan, dan arsitektur; antarmuka pemrograman aplikasi; dan praktik pemrograman untuk memfasilitasi manajemen, integrasi, dan keamanan sistem yang mendukung organisasi.', 'desc_bk_en' => 'This course material discusses several topics related to application programming, namely scripting languages, their use, and architecture; application programming interfaces; and programming practices to facilitate the management, integration, and security of systems that support organizations.'],
            ['id_bk' => 23, 'id_ps' => 7, 'nama_kode_bk'=>'BK-5', 'nama_bk_id' => 'Teknologi Platform', 'nama_bk_en' => 'Platform Technology', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini membahas perbandingan berbagai sistem operasi yang ada, termasuk karakteristik, kelebihan dan kekurangannya masing-masing. Pemilihan, penerapan, integrasi, dan administrasi platform atau komponen untuk mendukung infrastruktur TI organisasi. Dasar-dasar perangkat keras dan perangkat lunak dan cara integrasinya membentuk komponen penting dari sistem TI.', 'desc_bk_en' => 'This course material discusses the comparison of various existing operating systems, including their respective characteristics, advantages, and disadvantages. It covers the selection, implementation, integration, and administration of platforms or components to support an organization\'s IT infrastructure. It also covers the fundamentals of hardware and software and how they integrate to form important components of IT systems.'],
            ['id_bk' => 24, 'id_ps' => 7, 'nama_kode_bk'=>'BK-6', 'nama_bk_id' => 'Pengembangan Aplikasi Berbasis Platform', 'nama_bk_en' => 'Platform-Based Application Development', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini membahas berbagai topik terkait desain, pengembangan, dan implementasi aplikasi web, aplikasi seluler, dan platform industri. Materi pada bahan kajian ini mencakup gambaran umum tentang desain aplikasi web yang responsif, pengembangan aplikasi seluler yang efisien dan aman, simulasi platform industri, tugas pemrograman melalui API, dan analisis kerentanan keamanan dalam sistem industri seluler.', 'desc_bk_en' => 'This course material discusses various topics related to the design, development, and implementation of web applications, mobile applications, and industrial platforms. The material in this course covers an overview of responsive web application design, efficient and secure mobile application development, industrial platform simulation, programming tasks via APIs, and analysis of security vulnerabilities in mobile industrial systems.'],
            ['id_bk' => 25, 'id_ps' => 7, 'nama_kode_bk'=>'BK-7', 'nama_bk_id' => 'Prinsip-prinsip Keamanan Siber', 'nama_bk_en' => 'Principles of Cybersecurity', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini membahas tentang disiplin berbasis computing yang melibatkan teknologi, manusia, informasi, dan proses untuk memungkinkan operasi yang terjamin. Terdapat fokus pada implementasi, operasi, analisis, dan pengujian keamanan teknologi computing. Selain itu, juga terdapat pembahasan mengenai pengakuan sifat interdisipliner dari penerapan cybersecurity termasuk aspek hukum, kebijakan, faktor manusia, etika, dan manajemen risiko dalam konteks musuh.', 'desc_bk_en' => 'This course material discusses the discipline of computing-based security which involves technology, people, information, and processes to enable guaranteed operations. There is a focus on the implementation, operation, analysis, and testing of computing technology security. In addition, it discusses the recognition of the interdisciplinary nature of cybersecurity implementation including legal aspects, policies, human factors, ethics, and risk management in the context of adversaries.'],
            ['id_bk' => 26, 'id_ps' => 7, 'nama_kode_bk'=>'BK-8', 'nama_bk_id' => 'Praktek Profesional Global', 'nama_bk_en' => 'Global Professional Practice', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini membahas Pentingnya mengidentifikasi dan memahami keterampilan penting yang diperlukan untuk karier yang sukses dalam industri, termasuk keterampilan komunikasi lisan dan tertulis profesional. mengidentifikasikan cara kerja tim terintegrasi di seluruh TI dan cara TI mendukung organisasi serta Konteks sosial dan profesional teknologi informasi dan computing, dan kepatuhan terhadap kode etik perilaku.', 'desc_bk_en' => 'This course material discusses the importance of identifying and understanding the essential skills required for a successful career in the industry, including professional oral and written communication skills. It identifies how integrated teams work across IT and how IT supports organizations, as well as the social and professional context of information technology and computing, and compliance with codes of ethical conduct.'],
            ['id_bk' => 27, 'id_ps' => 7, 'nama_kode_bk'=>'BK-9', 'nama_bk_id' => 'Manajemen Data dan Informasi', 'nama_bk_en' => 'Data and Information Management', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini membahas tentang alat dan teknik untuk pemodelan, pengumpulan, pengorganisasian, pengambilan, dan pengelolaan data yang efisien, mengekstrak informasi dari data untuk membuat data bermakna bagi organisasi. Selain itu melakukan mengembangkan, menyebarkan, mengelola, dan mengintegrasikan sistem data dan informasi untuk mendukung organisasi serta memberikan solusi dari Masalah keselamatan dan keamanan yang terkait dengan data dan informasi.', 'desc_bk_en' => 'This course material discusses tools and techniques for modeling, collecting, organizing, retrieving, and efficiently managing data, extracting information from data to make the data meaningful for the organization. In addition, it covers developing, deploying, managing, and integrating data and information systems to support the organization and provide solutions for safety and security issues related to data and information.'],
            ['id_bk' => 28, 'id_ps' => 7, 'nama_kode_bk'=>'BK-10', 'nama_bk_id' => 'Fundamental Perangkat Lunak', 'nama_bk_en' => 'Software Fundamentals', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini membahas tentang pemrograman, yang mencakup keterampilan dan konsep dasar pemrograman, struktur data, dan proses algoritmik. Selain itu, juga dibahas strategi dan praktik pemrograman untuk pemecahan masalah yang efisien serta paradigma pemrograman untuk memecahkan berbagai masalah pemrograman.', 'desc_bk_en' => 'This course material discusses programming, which includes basic programming skills and concepts, data structures, and algorithmic processes. In addition, it discusses programming strategies and practices for efficient problem-solving and programming paradigms for solving various programming problems.'],
            ['id_bk' => 29, 'id_ps' => 7, 'nama_kode_bk'=>'BK-11', 'nama_bk_id' => 'Desain User Experience', 'nama_bk_en' => 'User Experience Design', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini membahas tentang pengembangan aplikasi dan sistem TI dengan fokus pada pengguna, yang mencakup pemahaman desain bagi pengguna, pengembangan pola pikir yang mengakui pentingnya pengguna, metodologi berpusat pada pengguna, penerapan kriteria evaluasi dan standar, serta analisis pengguna dan tugas, faktor manusia, ergonomi, aksesibilitas standar, desain pengalaman, dan psikologi kognitif.', 'desc_bk_en' => 'This course material discusses the development of IT applications and systems with a focus on the user, which includes understanding user-centered design, developing a mindset that recognizes the importance of the user, user-centered methodologies, applying evaluation criteria and standards, and user and task analysis, human factors, ergonomics, accessibility standards, experience design, and cognitive psychology.'],
            ['id_bk' => 30, 'id_ps' => 7, 'nama_kode_bk'=>'BK-12', 'nama_bk_id' => 'Tata kelola dan Kebijakan Keamanan Siber', 'nama_bk_en' => 'Cybersecurity Governance and Policy', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini membahas topik masalah dan prinsip keamanan, termasuk kerahasiaan, integritas, ketersediaan, otentikasi, otorisasi, non-repudiasi, dan akuntabilitas dalam sistem komputasi. Topik ini juga mencakup pentingnya tata kelola, mengidentifikasi risiko dan kerentanan potensial, menerapkan tindakan keamanan yang tepat, serta memahami isu hukum dan etika terkait keamanan.', 'desc_bk_en' => 'This course material discusses security issues and principles, including confidentiality, integrity, availability, authentication, authorization, non-repudiation, and accountability in computing systems. This topic also covers the importance of governance, identifying potential risks and vulnerabilities, implementing appropriate security measures, and understanding legal and ethical issues related to security.'],
            ['id_bk' => 31, 'id_ps' => 7, 'nama_kode_bk'=>'BK-13', 'nama_bk_id' => 'Manajemen Proyek', 'nama_bk_en' => 'Project Management', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini membahas beberapa topik terkait manajemen proyek, yaitu PMBOK dan siklus hidup proyek, elemen utama manajemen untuk tim proyek kecil, aspek-aspek manajerial dalam tim proyek kecil, pengembangan dan implementasi rencana pengukuran proses perangkat lunak, serta kerja efektif dengan anggota tim lainnya dalam kegiatan manajemen proyek.', 'desc_bk_en' => 'This course material discusses several topics related to project management, namely PMBOK and the project life cycle, key management elements for small project teams, managerial aspects in small project teams, development and implementation of a software process measurement plan, and effective work with other team members in project management activities.'],
            ['id_bk' => 32, 'id_ps' => 7, 'nama_kode_bk'=>'BK-14', 'nama_bk_id' => 'Teknologi dan Implementasi Keamanan Siber', 'nama_bk_en' => 'Cybersecurity Technology and Implementation', 'kategori' => 'Penciri Utama', 'desc_bk_id' => 'Bahan kajian ini mencakup topik seperti prinsip desain yang aman, kerentanan umum dalam perangkat lunak dan jaringan, teknik penyimpanan dan transmisi data yang aman, mekanisme kontrol akses, algoritma enkripsi, tanda tangan digital, metode otentikasi, sistem deteksi dan pencegahan intrusi, serta firewall.', 'desc_bk_en' => 'This course material covers topics such as secure design principles, common vulnerabilities in software and networks, secure data storage and transmission techniques, access control mechanisms, encryption algorithms, digital signatures, authentication methods, intrusion detection and prevention systems, and firewalls.'],

            // Teknik Elektro (id_ps = 8)
            ['id_bk' => 33, 'id_ps' => 8, 'nama_kode_bk'=>'BK-1', 'nama_bk_id' => 'Sistem Tenaga Listrik', 'nama_bk_en' => 'Electrical Power Systems', 'kategori' => 'Inti', 'desc_bk_id' => 'Pembangkitan, transmisi, dan distribusi tenaga listrik.', 'desc_bk_en' => 'Generation, transmission, and distribution of electric power.'],
            ['id_bk' => 34, 'id_ps' => 8, 'nama_kode_bk'=>'BK-2', 'nama_bk_id' => 'Rangkaian Elektronika', 'nama_bk_en' => 'Electronic Circuits', 'kategori' => 'Inti', 'desc_bk_id' => 'Analisis dan perancangan rangkaian elektronik analog dan digital.', 'desc_bk_en' => 'Analysis and design of analog and digital electronic circuits.'],
            ['id_bk' => 35, 'id_ps' => 8, 'nama_kode_bk'=>'BK-3', 'nama_bk_id' => 'Sistem Telekomunikasi', 'nama_bk_en' => 'Telecommunication Systems', 'kategori' => 'Inti', 'desc_bk_id' => 'Prinsip-prinsip sistem komunikasi nirkabel dan optik.', 'desc_bk_en' => 'Principles of wireless and optical communication systems.'],

            // Teknik Geologi (id_ps = 9)
            ['id_bk' => 36, 'id_ps' => 9, 'nama_kode_bk'=>'BK-1', 'nama_bk_id' => 'Geologi Struktur', 'nama_bk_en' => 'Structural Geology', 'kategori' => 'Inti', 'desc_bk_id' => 'Studi tentang deformasi batuan dan struktur kerak bumi.', 'desc_bk_en' => 'Study of rock deformation and Earth\'s crustal structures.'],
            ['id_bk' => 37, 'id_ps' => 9, 'nama_kode_bk'=>'BK-2', 'nama_bk_id' => 'Petrologi dan Mineralogi', 'nama_bk_en' => 'Petrology and Mineralogy', 'kategori' => 'Inti', 'desc_bk_id' => 'Identifikasi dan analisis batuan dan mineral.', 'desc_bk_en' => 'Identification and analysis of rocks and minerals.'],
            ['id_bk' => 38, 'id_ps' => 9, 'nama_kode_bk'=>'BK-3', 'nama_bk_id' => 'Geofisika dan Geokimia', 'nama_bk_en' => 'Geophysics and Geochemistry', 'kategori' => 'Inti', 'desc_bk_id' => 'Metode survei bawah permukaan dan analisis kimia batuan.', 'desc_bk_en' => 'Subsurface survey methods and chemical analysis of rocks.'],
        ]);
    }
}