<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MataKuliahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mata_kuliah')->insert([
            // kurikulum 2020
            // Program Studi 1: Teknik Sipil
            ['id_mk' => 1, 'id_kurikulum' => 1, 'id_ps' => 1, 'kode_mk'=>'MK-1', 'nama_matkul_id' => 'Mekanika Teknik', 'nama_matkul_en' => 'Engineering Mechanics', 'matkul_desc_id' => 'Mempelajari keseimbangan dan gerak benda padat serta aplikasinya dalam rekayasa.', 'matkul_desc_en' => 'Studies the equilibrium and motion of solid bodies and their application in engineering.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 2, 'id_kurikulum' => 1, 'id_ps' => 1, 'kode_mk'=>'MK-2', 'nama_matkul_id' => 'Struktur Beton', 'nama_matkul_en' => 'Concrete Structures', 'matkul_desc_id' => 'Analisis dan perancangan elemen-elemen struktur beton bertulang.', 'matkul_desc_en' => 'Analysis and design of reinforced concrete structural elements.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 3, 'id_kurikulum' => 1, 'id_ps' => 1, 'kode_mk'=>'MK-3', 'nama_matkul_id' => 'Hidrolika', 'nama_matkul_en' => 'Hydraulics', 'matkul_desc_id' => 'Studi tentang sifat-sifat mekanis fluida dan aplikasinya dalam sistem aliran.', 'matkul_desc_en' => 'Study of the mechanical properties of fluids and their application in flow systems.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 4, 'id_kurikulum' => 1, 'id_ps' => 1, 'kode_mk'=>'MK-4', 'nama_matkul_id' => 'Manajemen Konstruksi', 'nama_matkul_en' => 'Construction Management', 'matkul_desc_id' => 'Prinsip-prinsip perencanaan, pengorganisasian, dan pengendalian proyek konstruksi.', 'matkul_desc_en' => 'Principles of planning, organizing, and controlling construction projects.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 5, 'id_kurikulum' => 1, 'id_ps' => 1, 'kode_mk'=>'MK-5', 'nama_matkul_id' => 'Geoteknik', 'nama_matkul_en' => 'Geotechnics', 'matkul_desc_id' => 'Mempelajari perilaku tanah dan batuan serta interaksinya dengan struktur rekayasa.', 'matkul_desc_en' => 'Studies the behavior of soil and rock and their interaction with engineering structures.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 2: Teknik Pertambangan
            ['id_mk' => 6, 'id_kurikulum' => 2, 'id_ps' => 2, 'kode_mk'=>'MK-1', 'nama_matkul_id' => 'Geologi Dasar', 'nama_matkul_en' => 'Basic Geology', 'matkul_desc_id' => 'Pengenalan tentang material bumi, proses geologi, dan struktur kerak bumi.', 'matkul_desc_en' => 'Introduction to earth materials, geological processes, and the structure of the Earth\'s crust.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 7, 'id_kurikulum' => 2, 'id_ps' => 2, 'kode_mk'=>'MK-2', 'nama_matkul_id' => 'Eksplorasi Tambang', 'nama_matkul_en' => 'Mining Exploration', 'matkul_desc_id' => 'Metode pencarian dan penemuan deposit mineral yang bernilai ekonomis.', 'matkul_desc_en' => 'Methods of searching for and discovering economically valuable mineral deposits.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 8, 'id_kurikulum' => 2, 'id_ps' => 2, 'kode_mk'=>'MK-3', 'nama_matkul_id' => 'Penambangan Permukaan', 'nama_matkul_en' => 'Surface Mining', 'matkul_desc_id' => 'Teknik dan metode penambangan yang dilakukan di permukaan bumi.', 'matkul_desc_en' => 'Techniques and methods of mining conducted on the Earth\'s surface.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 9, 'id_kurikulum' => 2, 'id_ps' => 2, 'kode_mk'=>'MK-4', 'nama_matkul_id' => 'Ventilasi Tambang', 'nama_matkul_en' => 'Mine Ventilation', 'matkul_desc_id' => 'Pengendalian aliran udara di dalam tambang bawah tanah untuk menyediakan lingkungan kerja yang aman.', 'matkul_desc_en' => 'Control of airflow within underground mines to provide a safe working environment.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 10, 'id_kurikulum' => 2, 'id_ps' => 2, 'kode_mk'=>'MK-5', 'nama_matkul_id' => 'Evaluasi Cadangan', 'nama_matkul_en' => 'Reserve Evaluation', 'matkul_desc_id' => 'Penilaian kuantitas dan kualitas cadangan mineral untuk menentukan kelayakan tambang.', 'matkul_desc_en' => 'Assessment of the quantity and quality of mineral reserves to determine mine feasibility.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 3: Teknik Mesin
            ['id_mk' => 11, 'id_kurikulum' => 3, 'id_ps' => 3, 'kode_mk'=>'MK-1', 'nama_matkul_id' => 'Termodinamika', 'nama_matkul_en' => 'Thermodynamics', 'matkul_desc_id' => 'Studi tentang hubungan antara panas, kerja, dan energi dalam sistem fisik.', 'matkul_desc_en' => 'Study of the relationship between heat, work, and energy in physical systems.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 12, 'id_kurikulum' => 3, 'id_ps' => 3, 'kode_mk'=>'MK-2', 'nama_matkul_id' => 'Mekanika Fluida', 'nama_matkul_en' => 'Fluid Mechanics', 'matkul_desc_id' => 'Mempelajari perilaku fluida (cair dan gas) dalam keadaan diam dan bergerak.', 'matkul_desc_en' => 'Studies the behavior of fluids (liquids and gases) at rest and in motion.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 13, 'id_kurikulum' => 3, 'id_ps' => 3, 'kode_mk'=>'MK-3', 'nama_matkul_id' => 'Konversi Energi', 'nama_matkul_en' => 'Energy Conversion', 'matkul_desc_id' => 'Proses perubahan energi dari satu bentuk ke bentuk lain, seperti dari panas ke mekanik.', 'matkul_desc_en' => 'The process of changing energy from one form to another, such as from heat to mechanical.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 14, 'id_kurikulum' => 3, 'id_ps' => 3, 'kode_mk'=>'MK-4', 'nama_matkul_id' => 'Perpindahan Panas', 'nama_matkul_en' => 'Heat Transfer', 'matkul_desc_id' => 'Mekanisme perpindahan energi termal melalui konduksi, konveksi, dan radiasi.', 'matkul_desc_en' => 'Mechanisms of thermal energy transfer through conduction, convection, and radiation.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 15, 'id_kurikulum' => 3, 'id_ps' => 3, 'kode_mk'=>'MK-5', 'nama_matkul_id' => 'Desain Mesin', 'nama_matkul_en' => 'Machine Design', 'matkul_desc_id' => 'Penerapan prinsip-prinsip rekayasa untuk merancang komponen dan sistem mesin.', 'matkul_desc_en' => 'Application of engineering principles to design machine components and systems.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 4: Teknik Lingkungan
            ['id_mk' => 16, 'id_kurikulum' => 4, 'id_ps' => 4, 'kode_mk'=>'MK-1', 'nama_matkul_id' => 'Kimia Lingkungan', 'nama_matkul_en' => 'Environmental Chemistry', 'matkul_desc_id' => 'Studi tentang proses kimia yang terjadi di lingkungan alam (udara, air, tanah).', 'matkul_desc_en' => 'Study of chemical processes that occur in the natural environment (air, water, soil).', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 17, 'id_kurikulum' => 4, 'id_ps' => 4, 'kode_mk'=>'MK-2', 'nama_matkul_id' => 'Teknologi Air Bersih', 'nama_matkul_en' => 'Clean Water Technology', 'matkul_desc_id' => 'Metode pengolahan air untuk menghasilkan air yang aman untuk dikonsumsi.', 'matkul_desc_en' => 'Water treatment methods to produce water that is safe for consumption.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 18, 'id_kurikulum' => 4, 'id_ps' => 4, 'kode_mk'=>'MK-3', 'nama_matkul_id' => 'Pengelolaan Limbah', 'nama_matkul_en' => 'Waste Management', 'matkul_desc_id' => 'Prinsip dan praktik pengumpulan, pengolahan, dan pembuangan limbah padat dan cair.', 'matkul_desc_en' => 'Principles and practices of collecting, treating, and disposing of solid and liquid waste.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 19, 'id_kurikulum' => 4, 'id_ps' => 4, 'kode_mk'=>'MK-4', 'nama_matkul_id' => 'EKL dan AMDAL', 'nama_matkul_en' => 'EKL and AMDAL', 'matkul_desc_id' => 'Studi mengenai evaluasi dampak lingkungan dari suatu proyek atau kegiatan.', 'matkul_desc_en' => 'Study concerning the environmental impact assessment of a project or activity.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 20, 'id_kurikulum' => 4, 'id_ps' => 4, 'kode_mk'=>'MK-5', 'nama_matkul_id' => 'Teknologi Lingkungan', 'nama_matkul_en' => 'Environmental Technology', 'matkul_desc_id' => 'Penerapan ilmu pengetahuan dan rekayasa untuk melindungi dan memulihkan lingkungan.', 'matkul_desc_en' => 'Application of science and engineering to protect and restore the environment.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 5: Arsitektur
            ['id_mk' => 21, 'id_kurikulum' => 5, 'id_ps' => 5, 'kode_mk'=>'MK-1', 'nama_matkul_id' => 'Dasar Desain Arsitektur', 'nama_matkul_en' => 'Fundamentals of Architectural Design', 'matkul_desc_id' => 'Pengenalan prinsip-prinsip dasar dalam perancangan ruang dan bentuk arsitektur.', 'matkul_desc_en' => 'Introduction to the basic principles in the design of architectural space and form.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 22, 'id_kurikulum' => 5, 'id_ps' => 5, 'kode_mk'=>'MK-2', 'nama_matkul_id' => 'Arsitektur Vernakular', 'nama_matkul_en' => 'Vernacular Architecture', 'matkul_desc_id' => 'Studi tentang arsitektur tradisional yang tumbuh dari budaya dan material lokal.', 'matkul_desc_en' => 'Study of traditional architecture that grows from local culture and materials.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 23, 'id_kurikulum' => 5, 'id_ps' => 5, 'kode_mk'=>'MK-3', 'nama_matkul_id' => 'Teknologi Bangunan', 'nama_matkul_en' => 'Building Technology', 'matkul_desc_id' => 'Mempelajari material, struktur, dan sistem konstruksi dalam bangunan.', 'matkul_desc_en' => 'Studies materials, structures, and construction systems in buildings.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 24, 'id_kurikulum' => 5, 'id_ps' => 5, 'kode_mk'=>'MK-4', 'nama_matkul_id' => 'Perancangan Kota', 'nama_matkul_en' => 'Urban Design', 'matkul_desc_id' => 'Proses merancang dan membentuk fitur fisik kota atau perkotaan.', 'matkul_desc_en' => 'The process of designing and shaping the physical features of cities or urban areas.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 25, 'id_kurikulum' => 5, 'id_ps' => 5, 'kode_mk'=>'MK-5', 'nama_matkul_id' => 'Manajemen Proyek Arsitektur', 'nama_matkul_en' => 'Architectural Project Management', 'matkul_desc_id' => 'Pengelolaan proyek arsitektur dari tahap konsep hingga penyelesaian konstruksi.', 'matkul_desc_en' => 'Management of architectural projects from the concept stage to construction completion.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 6: Teknik Kimia
            ['id_mk' => 26, 'id_kurikulum' => 6, 'id_ps' => 6, 'kode_mk'=>'MK-1', 'nama_matkul_id' => 'Kimia Dasar', 'nama_matkul_en' => 'Basic Chemistry', 'matkul_desc_id' => 'Konsep fundamental kimia, termasuk struktur atom, ikatan kimia, dan stoikiometri.', 'matkul_desc_en' => 'Fundamental concepts of chemistry, including atomic structure, chemical bonding, and stoichiometry.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 27, 'id_kurikulum' => 6, 'id_ps' => 6, 'kode_mk'=>'MK-2', 'nama_matkul_id' => 'Perpindahan Massa', 'nama_matkul_en' => 'Mass Transfer', 'matkul_desc_id' => 'Perpindahan komponen kimia antara fasa yang berbeda, seperti dalam distilasi atau absorpsi.', 'matkul_desc_en' => 'The movement of chemical components between different phases, such as in distillation or absorption.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 28, 'id_kurikulum' => 6, 'id_ps' => 6, 'kode_mk'=>'MK-3', 'nama_matkul_id' => 'Rekayasa Reaksi Kimia', 'nama_matkul_en' => 'Chemical Reaction Engineering', 'matkul_desc_id' => 'Perancangan dan operasi reaktor kimia untuk produksi skala industri.', 'matkul_desc_en' => 'Design and operation of chemical reactors for industrial-scale production.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 29, 'id_kurikulum' => 6, 'id_ps' => 6, 'kode_mk'=>'MK-4', 'nama_matkul_id' => 'Instrumentasi Proses', 'nama_matkul_en' => 'Process Instrumentation', 'matkul_desc_id' => 'Pengukuran dan pengendalian variabel proses seperti suhu, tekanan, dan laju alir.', 'matkul_desc_en' => 'Measurement and control of process variables such as temperature, pressure, and flow rate.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 30, 'id_kurikulum' => 6, 'id_ps' => 6, 'kode_mk'=>'MK-5', 'nama_matkul_id' => 'Manajemen Industri Kimia', 'nama_matkul_en' => 'Chemical Industry Management', 'matkul_desc_id' => 'Aspek bisnis dan manajemen dalam operasi industri kimia.', 'matkul_desc_en' => 'Business and management aspects in the operation of the chemical industry.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 7: Teknologi Informasi
            // ['id_mk' => 31, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'MK-1', 'nama_matkul_id' => 'Algoritma dan Pemrograman', 'nama_matkul_en' => 'Algorithms and Programming', 'matkul_desc_id' => 'Dasar-dasar logika pemrograman, penyelesaian masalah, dan implementasi algoritma.', 'matkul_desc_en' => 'Fundamentals of programming logic, problem-solving, and algorithm implementation.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121],
            // ['id_mk' => 32, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'MK-2', 'nama_matkul_id' => 'Struktur Data', 'nama_matkul_en' => 'Data Structures', 'matkul_desc_id' => 'Cara mengorganisir dan menyimpan data dalam komputer agar dapat digunakan secara efisien.', 'matkul_desc_en' => 'Ways to organize and store data in a computer so that it can be used efficiently.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap', 'id_pengembang_rps' => 123, 'id_koordinator_mk' => 121],
            // ['id_mk' => 33, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'MK-3', 'nama_matkul_id' => 'Basis Data', 'nama_matkul_en' => 'Databases', 'matkul_desc_id' => 'Konsep dan implementasi sistem untuk mengelola kumpulan data yang besar dan terstruktur.', 'matkul_desc_en' => 'Concepts and implementation of systems for managing large and structured collections of data.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121],
            // ['id_mk' => 34, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'MK-4', 'nama_matkul_id' => 'Interaksi Manusia Komputer', 'nama_matkul_en' => 'Human-Computer Interaction', 'matkul_desc_id' => 'Mata kuliah ini membahas prinsip dasar Interaksi Manusia dan Komputer (IMK) serta pendekatan perancangan antarmuka pengguna yang ergonomis, efektif, dan berpusat pada pengguna. Cakupan materi meliputi aspek psikologis dan kognitif pengguna, model mental, teknik pengumpulan data, pembuatan persona dan skenario, serta desain wireframe dan prototype. Mahasiswa juga akan mempelajari evaluasi usability, tren teknologi interaktif seperti AR/VR dan gesture interaction, serta isu etika dalam desain antarmuka. Melalui mata kuliah ini, mahasiswa mampu merancang dan mengevaluasi antarmuka yang inovatif, fungsional, dan bertanggung jawab. ', 'matkul_desc_en' => 'This course provides a fundamental understanding of Human-Computer Interaction (HCI), focusing on the design and evaluation of computational systems that are effective, efficient, and satisfying. The material covers the psychological and cognitive aspects of users, mental models, data collection techniques, persona creation, and prototype design. Students will also learn about usability evaluation, future interactive technology trends such as AR/VR, and ethical issues in interface design. Through this course, students will be able to design and evaluate innovative, functional, and responsible interfaces.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap', 'id_pengembang_rps' => 123, 'id_koordinator_mk' => 121],
            // ['id_mk' => 35, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'MK-5', 'nama_matkul_id' => 'Pemrograman Web II', 'nama_matkul_en' => 'Web Programming II', 'matkul_desc_id' => 'Studi tentang bagaimana membuat komputer dapat melakukan tugas yang memerlukan kecerdasan manusia.', 'matkul_desc_en' => 'The study of how to make computers perform tasks that require human intelligence.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua', 'id_pengembang_rps' => 127, 'id_koordinator_mk' => 121],
            // ['id_mk' => 36, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'MK-6', 'nama_matkul_id' => 'Praktikum Pemrograman Web II', 'nama_matkul_en' => 'Web Programing Practicum II', 'matkul_desc_id' => 'Studi tentang bagaimana membuat komputer dapat melakukan tugas yang memerlukan kecerdasan manusia.', 'matkul_desc_en' => 'The study of how to make computers perform tasks that require human intelligence.', 'sks_teori' => 0, 'sks_praktikum' => 2, 'semester' => 5, 'muncul' => 'semua', 'id_pengembang_rps' => 122, 'id_koordinator_mk' => 121],

            // Program Studi 8: Teknik Elektro
            ['id_mk' => 37, 'id_kurikulum' => 8, 'id_ps' => 8, 'kode_mk'=>'MK-1', 'nama_matkul_id' => 'Dasar-Dasar Listrik', 'nama_matkul_en' => 'Fundamentals of Electricity', 'matkul_desc_id' => 'Hukum dan konsep dasar rangkaian listrik arus searah dan bolak-balik.', 'matkul_desc_en' => 'Basic laws and concepts of direct current and alternating current electrical circuits.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 38, 'id_kurikulum' => 8, 'id_ps' => 8, 'kode_mk'=>'MK-2', 'nama_matkul_id' => 'Elektronika Dasar', 'nama_matkul_en' => 'Basic Electronics', 'matkul_desc_id' => 'Mempelajari komponen elektronik seperti dioda, transistor, dan op-amp serta aplikasinya.', 'matkul_desc_en' => 'Studies electronic components such as diodes, transistors, and op-amps and their applications.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 39, 'id_kurikulum' => 8, 'id_ps' => 8, 'kode_mk'=>'MK-3', 'nama_matkul_id' => 'Sistem Digital', 'nama_matkul_en' => 'Digital Systems', 'matkul_desc_id' => 'Logika digital, aljabar Boolean, dan perancangan rangkaian kombinasional dan sekuensial.', 'matkul_desc_en' => 'Digital logic, Boolean algebra, and the design of combinational and sequential circuits.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 40, 'id_kurikulum' => 8, 'id_ps' => 8, 'kode_mk'=>'MK-4', 'nama_matkul_id' => 'Mikrokontroler', 'nama_matkul_en' => 'Microcontrollers', 'matkul_desc_id' => 'Arsitektur dan pemrograman perangkat mikrokontroler untuk sistem tertanam.', 'matkul_desc_en' => 'Architecture and programming of microcontroller devices for embedded systems.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 41, 'id_kurikulum' => 8, 'id_ps' => 8, 'kode_mk'=>'MK-5', 'nama_matkul_id' => 'Sistem Kendali', 'nama_matkul_en' => 'Control Systems', 'matkul_desc_id' => 'Analisis dan perancangan sistem untuk mengendalikan perilaku sistem dinamis.', 'matkul_desc_en' => 'Analysis and design of systems to control the behavior of dynamic systems.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 9: Teknik Geologi
            ['id_mk' => 42, 'id_kurikulum' => 9, 'id_ps' => 9, 'kode_mk'=>'MK-1', 'nama_matkul_id' => 'Geologi Fisik', 'nama_matkul_en' => 'Physical Geology', 'matkul_desc_id' => 'Mempelajari proses-proses fisik yang membentuk dan mengubah permukaan bumi.', 'matkul_desc_en' => 'Studies the physical processes that shape and change the Earth\'s surface.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 43, 'id_kurikulum' => 9, 'id_ps' => 9, 'kode_mk'=>'MK-2', 'nama_matkul_id' => 'Mineralogi', 'nama_matkul_en' => 'Mineralogy', 'matkul_desc_id' => 'Studi tentang mineral, termasuk identifikasi, kristalografi, dan sifat fisiknya.', 'matkul_desc_en' => 'The study of minerals, including their identification, crystallography, and physical properties.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 44, 'id_kurikulum' => 9, 'id_ps' => 9, 'kode_mk'=>'MK-3', 'nama_matkul_id' => 'Petrologi', 'nama_matkul_en' => 'Petrology', 'matkul_desc_id' => 'Studi tentang asal-usul, komposisi, dan klasifikasi batuan.', 'matkul_desc_en' => 'The study of the origin, composition, and classification of rocks.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 45, 'id_kurikulum' => 9, 'id_ps' => 9, 'kode_mk'=>'MK-4', 'nama_matkul_id' => 'Struktur Geologi', 'nama_matkul_en' => 'Structural Geology', 'matkul_desc_id' => 'Analisis deformasi batuan dan struktur geologi seperti lipatan dan sesar.', 'matkul_desc_en' => 'Analysis of rock deformation and geological structures such as folds and faults.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 46, 'id_kurikulum' => 9, 'id_ps' => 9, 'kode_mk'=>'MK-5', 'nama_matkul_id' => 'Geologi Teknik', 'nama_matkul_en' => 'Engineering Geology', 'matkul_desc_id' => 'Penerapan prinsip geologi dalam praktik rekayasa, khususnya untuk proyek konstruksi.', 'matkul_desc_en' => 'Application of geological principles in engineering practice, especially for construction projects.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Lanjutan untuk kurikulum 2025
            // Program Studi 1: Teknik Sipil
            ['id_mk' => 47, 'id_kurikulum' => 10, 'id_ps' => 1, 'kode_mk'=>'(2025)MK-1', 'nama_matkul_id' => 'Mekanika Teknik (2025)', 'nama_matkul_en' => 'Engineering Mechanics (2025)', 'matkul_desc_id' => 'Mempelajari keseimbangan dan gerak benda padat serta aplikasinya dalam rekayasa. (2025)', 'matkul_desc_en' => 'Studies the equilibrium and motion of solid bodies and their application in engineering. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 48, 'id_kurikulum' => 10, 'id_ps' => 1, 'kode_mk'=>'(2025)MK-2', 'nama_matkul_id' => 'Struktur Beton (2025)', 'nama_matkul_en' => 'Concrete Structures (2025)', 'matkul_desc_id' => 'Analisis dan perancangan elemen-elemen struktur beton bertulang. (2025)', 'matkul_desc_en' => 'Analysis and design of reinforced concrete structural elements. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 49, 'id_kurikulum' => 10, 'id_ps' => 1, 'kode_mk'=>'(2025)MK-3', 'nama_matkul_id' => 'Hidrolika (2025)', 'nama_matkul_en' => 'Hydraulics (2025)', 'matkul_desc_id' => 'Studi tentang sifat-sifat mekanis fluida dan aplikasinya dalam sistem aliran. (2025)', 'matkul_desc_en' => 'Study of the mechanical properties of fluids and their application in flow systems. (2025)', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 50, 'id_kurikulum' => 10, 'id_ps' => 1, 'kode_mk'=>'(2025)MK-4', 'nama_matkul_id' => 'Manajemen Konstruksi (2025)', 'nama_matkul_en' => 'Construction Management (2025)', 'matkul_desc_id' => 'Prinsip-prinsip perencanaan, pengorganisasian, dan pengendalian proyek konstruksi. (2025)', 'matkul_desc_en' => 'Principles of planning, organizing, and controlling construction projects. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 51, 'id_kurikulum' => 10, 'id_ps' => 1, 'kode_mk'=>'(2025)MK-5', 'nama_matkul_id' => 'Geoteknik (2025)', 'nama_matkul_en' => 'Geotechnics (2025)', 'matkul_desc_id' => 'Mempelajari perilaku tanah dan batuan serta interaksinya dengan struktur rekayasa. (2025)', 'matkul_desc_en' => 'Studies the behavior of soil and rock and their interaction with engineering structures. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 2: Teknik Pertambangan
            ['id_mk' => 52, 'id_kurikulum' => 11, 'id_ps' => 2, 'kode_mk'=>'(2025)MK-1', 'nama_matkul_id' => 'Geologi Dasar (2025)', 'nama_matkul_en' => 'Basic Geology (2025)', 'matkul_desc_id' => 'Pengenalan tentang material bumi, proses geologi, dan struktur kerak bumi. (2025)', 'matkul_desc_en' => 'Introduction to earth materials, geological processes, and the structure of the Earth\'s crust. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 53, 'id_kurikulum' => 11, 'id_ps' => 2, 'kode_mk'=>'(2025)MK-2', 'nama_matkul_id' => 'Eksplorasi Tambang (2025)', 'nama_matkul_en' => 'Mining Exploration (2025)', 'matkul_desc_id' => 'Metode pencarian dan penemuan deposit mineral yang bernilai ekonomis. (2025)', 'matkul_desc_en' => 'Methods of searching for and discovering economically valuable mineral deposits. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 54, 'id_kurikulum' => 11, 'id_ps' => 2, 'kode_mk'=>'(2025)MK-3', 'nama_matkul_id' => 'Penambangan Permukaan (2025)', 'nama_matkul_en' => 'Surface Mining (2025)', 'matkul_desc_id' => 'Teknik dan metode penambangan yang dilakukan di permukaan bumi. (2025)', 'matkul_desc_en' => 'Techniques and methods of mining conducted on the Earth\'s surface. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 55, 'id_kurikulum' => 11, 'id_ps' => 2, 'kode_mk'=>'(2025)MK-4', 'nama_matkul_id' => 'Ventilasi Tambang (2025)', 'nama_matkul_en' => 'Mine Ventilation (2025)', 'matkul_desc_id' => 'Pengendalian aliran udara di dalam tambang bawah tanah untuk menyediakan lingkungan kerja yang aman. (2025)', 'matkul_desc_en' => 'Control of airflow within underground mines to provide a safe working environment. (2025)', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 56, 'id_kurikulum' => 11, 'id_ps' => 2, 'kode_mk'=>'(2025)MK-5', 'nama_matkul_id' => 'Evaluasi Cadangan (2025)', 'nama_matkul_en' => 'Reserve Evaluation (2025)', 'matkul_desc_id' => 'Penilaian kuantitas dan kualitas cadangan mineral untuk menentukan kelayakan tambang. (2025)', 'matkul_desc_en' => 'Assessment of the quantity and quality of mineral reserves to determine mine feasibility. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 3: Teknik Mesin
            ['id_mk' => 57, 'id_kurikulum' => 12, 'id_ps' => 3, 'kode_mk'=>'(2025)MK-1', 'nama_matkul_id' => 'Termodinamika (2025)', 'nama_matkul_en' => 'Thermodynamics (2025)', 'matkul_desc_id' => 'Studi tentang hubungan antara panas, kerja, dan energi dalam sistem fisik. (2025)', 'matkul_desc_en' => 'Study of the relationship between heat, work, and energy in physical systems. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 58, 'id_kurikulum' => 12, 'id_ps' => 3, 'kode_mk'=>'(2025)MK-2', 'nama_matkul_id' => 'Mekanika Fluida (2025)', 'nama_matkul_en' => 'Fluid Mechanics (2025)', 'matkul_desc_id' => 'Mempelajari perilaku fluida (cair dan gas) dalam keadaan diam dan bergerak. (2025)', 'matkul_desc_en' => 'Studies the behavior of fluids (liquids and gases) at rest and in motion. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 59, 'id_kurikulum' => 12, 'id_ps' => 3, 'kode_mk'=>'(2025)MK-3', 'nama_matkul_id' => 'Konversi Energi (2025)', 'nama_matkul_en' => 'Energy Conversion (2025)', 'matkul_desc_id' => 'Proses perubahan energi dari satu bentuk ke bentuk lain, seperti dari panas ke mekanik. (2025)', 'matkul_desc_en' => 'The process of changing energy from one form to another, such as from heat to mechanical. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 60, 'id_kurikulum' => 12, 'id_ps' => 3, 'kode_mk'=>'(2025)MK-4', 'nama_matkul_id' => 'Perpindahan Panas (2025)', 'nama_matkul_en' => 'Heat Transfer (2025)', 'matkul_desc_id' => 'Mekanisme perpindahan energi termal melalui konduksi, konveksi, dan radiasi. (2025)', 'matkul_desc_en' => 'Mechanisms of thermal energy transfer through conduction, convection, and radiation. (2025)', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 61, 'id_kurikulum' => 12, 'id_ps' => 3, 'kode_mk'=>'(2025)MK-5', 'nama_matkul_id' => 'Desain Mesin (2025)', 'nama_matkul_en' => 'Machine Design (2025)', 'matkul_desc_id' => 'Penerapan prinsip-prinsip rekayasa untuk merancang komponen dan sistem mesin. (2025)', 'matkul_desc_en' => 'Application of engineering principles to design machine components and systems. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 4: Teknik Lingkungan
            ['id_mk' => 62, 'id_kurikulum' => 13, 'id_ps' => 4, 'kode_mk'=>'(2025)MK-1', 'nama_matkul_id' => 'Kimia Lingkungan (2025)', 'nama_matkul_en' => 'Environmental Chemistry (2025)', 'matkul_desc_id' => 'Studi tentang proses kimia yang terjadi di lingkungan alam (udara, air, tanah). (2025)', 'matkul_desc_en' => 'Study of chemical processes that occur in the natural environment (air, water, soil). (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 63, 'id_kurikulum' => 13, 'id_ps' => 4, 'kode_mk'=>'(2025)MK-2', 'nama_matkul_id' => 'Teknologi Air Bersih (2025)', 'nama_matkul_en' => 'Clean Water Technology (2025)', 'matkul_desc_id' => 'Metode pengolahan air untuk menghasilkan air yang aman untuk dikonsumsi. (2025)', 'matkul_desc_en' => 'Water treatment methods to produce water that is safe for consumption. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 64, 'id_kurikulum' => 13, 'id_ps' => 4, 'kode_mk'=>'(2025)MK-3', 'nama_matkul_id' => 'Pengelolaan Limbah (2025)', 'nama_matkul_en' => 'Waste Management (2025)', 'matkul_desc_id' => 'Prinsip dan praktik pengumpulan, pengolahan, dan pembuangan limbah padat dan cair. (2025)', 'matkul_desc_en' => 'Principles and practices of collecting, treating, and disposing of solid and liquid waste. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 65, 'id_kurikulum' => 13, 'id_ps' => 4, 'kode_mk'=>'(2025)MK-4', 'nama_matkul_id' => 'EKL dan AMDAL (2025)', 'nama_matkul_en' => 'EKL and AMDAL (2025)', 'matkul_desc_id' => 'Studi mengenai evaluasi dampak lingkungan dari suatu proyek atau kegiatan. (2025)', 'matkul_desc_en' => 'Study concerning the environmental impact assessment of a project or activity. (2025)', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 66, 'id_kurikulum' => 13, 'id_ps' => 4, 'kode_mk'=>'(2025)MK-5', 'nama_matkul_id' => 'Teknologi Lingkungan (2025)', 'nama_matkul_en' => 'Environmental Technology (2025)', 'matkul_desc_id' => 'Penerapan ilmu pengetahuan dan rekayasa untuk melindungi dan memulihkan lingkungan. (2025)', 'matkul_desc_en' => 'Application of science and engineering to protect and restore the environment. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 5: Arsitektur
            ['id_mk' => 67, 'id_kurikulum' => 14, 'id_ps' => 5, 'kode_mk'=>'(2025)MK-1', 'nama_matkul_id' => 'Dasar Desain Arsitektur (2025)', 'nama_matkul_en' => 'Fundamentals of Architectural Design (2025)', 'matkul_desc_id' => 'Pengenalan prinsip-prinsip dasar dalam perancangan ruang dan bentuk arsitektur. (2025)', 'matkul_desc_en' => 'Introduction to the basic principles in the design of architectural space and form. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 68, 'id_kurikulum' => 14, 'id_ps' => 5, 'kode_mk'=>'(2025)MK-2', 'nama_matkul_id' => 'Arsitektur Vernakular (2025)', 'nama_matkul_en' => 'Vernacular Architecture (2025)', 'matkul_desc_id' => 'Studi tentang arsitektur tradisional yang tumbuh dari budaya dan material lokal. (2025)', 'matkul_desc_en' => 'Study of traditional architecture that grows from local culture and materials. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 69, 'id_kurikulum' => 14, 'id_ps' => 5, 'kode_mk'=>'(2025)MK-3', 'nama_matkul_id' => 'Teknologi Bangunan (2025)', 'nama_matkul_en' => 'Building Technology (2025)', 'matkul_desc_id' => 'Mempelajari material, struktur, dan sistem konstruksi dalam bangunan. (2025)', 'matkul_desc_en' => 'Studies materials, structures, and construction systems in buildings. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 70, 'id_kurikulum' => 14, 'id_ps' => 5, 'kode_mk'=>'(2025)MK-4', 'nama_matkul_id' => 'Perancangan Kota (2025)', 'nama_matkul_en' => 'Urban Design (2025)', 'matkul_desc_id' => 'Proses merancang dan membentuk fitur fisik kota atau perkotaan. (2025)', 'matkul_desc_en' => 'The process of designing and shaping the physical features of cities or urban areas. (2025)', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 71, 'id_kurikulum' => 14, 'id_ps' => 5, 'kode_mk'=>'(2025)MK-5', 'nama_matkul_id' => 'Manajemen Proyek Arsitektur (2025)', 'nama_matkul_en' => 'Architectural Project Management (2025)', 'matkul_desc_id' => 'Pengelolaan proyek arsitektur dari tahap konsep hingga penyelesaian konstruksi. (2025)', 'matkul_desc_en' => 'Management of architectural projects from the concept stage to construction completion. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 6: Teknik Kimia
            ['id_mk' => 72, 'id_kurikulum' => 15, 'id_ps' => 6, 'kode_mk'=>'(2025)MK-1', 'nama_matkul_id' => 'Kimia Dasar (2025)', 'nama_matkul_en' => 'Basic Chemistry (2025)', 'matkul_desc_id' => 'Konsep fundamental kimia, termasuk struktur atom, ikatan kimia, dan stoikiometri. (2025)', 'matkul_desc_en' => 'Fundamental concepts of chemistry, including atomic structure, chemical bonding, and stoichiometry. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 73, 'id_kurikulum' => 15, 'id_ps' => 6, 'kode_mk'=>'(2025)MK-2', 'nama_matkul_id' => 'Perpindahan Massa (2025)', 'nama_matkul_en' => 'Mass Transfer (2025)', 'matkul_desc_id' => 'Perpindahan komponen kimia antara fasa yang berbeda, seperti dalam distilasi atau absorpsi. (2025)', 'matkul_desc_en' => 'The movement of chemical components between different phases, such as in distillation or absorption. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 74, 'id_kurikulum' => 15, 'id_ps' => 6, 'kode_mk'=>'(2025)MK-3', 'nama_matkul_id' => 'Rekayasa Reaksi Kimia (2025)', 'nama_matkul_en' => 'Chemical Reaction Engineering (2025)', 'matkul_desc_id' => 'Perancangan dan operasi reaktor kimia untuk produksi skala industri. (2025)', 'matkul_desc_en' => 'Design and operation of chemical reactors for industrial-scale production. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 75, 'id_kurikulum' => 15, 'id_ps' => 6, 'kode_mk'=>'(2025)MK-4', 'nama_matkul_id' => 'Instrumentasi Proses (2025)', 'nama_matkul_en' => 'Process Instrumentation (2025)', 'matkul_desc_id' => 'Pengukuran dan pengendalian variabel proses seperti suhu, tekanan, dan laju alir. (2025)', 'matkul_desc_en' => 'Measurement and control of process variables such as temperature, pressure, and flow rate. (2025)', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 76, 'id_kurikulum' => 15, 'id_ps' => 6, 'kode_mk'=>'(2025)MK-5', 'nama_matkul_id' => 'Manajemen Industri Kimia (2025)', 'nama_matkul_en' => 'Chemical Industry Management (2025)', 'matkul_desc_id' => 'Aspek bisnis dan manajemen dalam operasi industri kimia. (2025)', 'matkul_desc_en' => 'Business and management aspects in the operation of the chemical industry. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 7: Teknologi Informasi
            // ['id_mk' => 77, 'id_kurikulum' => 16, 'id_ps' => 7, 'kode_mk'=>'(2025)MK-1', 'nama_matkul_id' => 'Algoritma dan Pemrograman (2025)', 'nama_matkul_en' => 'Algorithms and Programming (2025)', 'matkul_desc_id' => 'Dasar-dasar logika pemrograman, penyelesaian masalah, dan implementasi algoritma. (2025)', 'matkul_desc_en' => 'Fundamentals of programming logic, problem-solving, and algorithm implementation. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => 123, 'id_koordinator_mk' => 126],
            // ['id_mk' => 78, 'id_kurikulum' => 16, 'id_ps' => 7, 'kode_mk'=>'(2025)MK-2', 'nama_matkul_id' => 'Struktur Data (2025)', 'nama_matkul_en' => 'Data Structures (2025)', 'matkul_desc_id' => 'Cara mengorganisir dan menyimpan data dalam komputer agar dapat digunakan secara efisien. (2025)', 'matkul_desc_en' => 'Ways to organize and store data in a computer so that it can be used efficiently. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => 126, 'id_koordinator_mk' => 129],
            // ['id_mk' => 79, 'id_kurikulum' => 16, 'id_ps' => 7, 'kode_mk'=>'(2025)MK-3', 'nama_matkul_id' => 'Basis Data (2025)', 'nama_matkul_en' => 'Databases (2025)', 'matkul_desc_id' => 'Konsep dan implementasi sistem untuk mengelola kumpulan data yang besar dan terstruktur. (2025)', 'matkul_desc_en' => 'Concepts and implementation of systems for managing large and structured collections of data. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => 129, 'id_koordinator_mk' => 130],
            // ['id_mk' => 80, 'id_kurikulum' => 16, 'id_ps' => 7, 'kode_mk'=>'(2025)MK-4', 'nama_matkul_id' => 'Interaksi Manusia Komputer (2025)', 'nama_matkul_en' => 'Human-Computer Interaction (2025)', 'matkul_desc_id' => 'Mata kuliah ini membahas prinsip dasar Interaksi Manusia dan Komputer (IMK) serta pendekatan perancangan antarmuka pengguna yang ergonomis, efektif, dan berpusat pada pengguna. Cakupan materi meliputi aspek psikologis dan kognitif pengguna, model mental, teknik pengumpulan data, pembuatan persona dan skenario, serta desain wireframe dan prototype. Mahasiswa juga akan mempelajari evaluasi usability, tren teknologi interaktif seperti AR/VR dan gesture interaction, serta isu etika dalam desain antarmuka. Melalui mata kuliah ini, mahasiswa mampu merancang dan mengevaluasi antarmuka yang inovatif, fungsional, dan bertanggung jawab (2025). ', 'matkul_desc_en' => 'This course provides a fundamental understanding of Human-Computer Interaction (HCI), focusing on the design and evaluation of computational systems that are effective, efficient, and satisfying. The material covers the psychological and cognitive aspects of users, mental models, data collection techniques, persona creation, and prototype design. Students will also learn about usability evaluation, future interactive technology trends such as AR/VR, and ethical issues in interface design. Through this course, students will be able to design and evaluate innovative, functional, and responsible interfaces.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => 123, 'id_koordinator_mk' => 124],
            // ['id_mk' => 81, 'id_kurikulum' => 16, 'id_ps' => 7, 'kode_mk'=>'(2025)MK-5', 'nama_matkul_id' => 'Kecerdasan Buatan (2025)', 'nama_matkul_en' => 'Artificial Intelligence (2025)', 'matkul_desc_id' => 'Studi tentang bagaimana membuat komputer dapat melakukan tugas yang memerlukan kecerdasan manusia. (2025)', 'matkul_desc_en' => 'The study of how to make computers perform tasks that require human intelligence. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => 127, 'id_koordinator_mk' => 124],

            // Program Studi 8: Teknik Elektro
            ['id_mk' => 82, 'id_kurikulum' => 17, 'id_ps' => 8, 'kode_mk'=>'(2025)MK-1', 'nama_matkul_id' => 'Dasar-Dasar Listrik (2025)', 'nama_matkul_en' => 'Fundamentals of Electricity (2025)', 'matkul_desc_id' => 'Hukum dan konsep dasar rangkaian listrik arus searah dan bolak-balik. (2025)', 'matkul_desc_en' => 'Basic laws and concepts of direct current and alternating current electrical circuits. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 83, 'id_kurikulum' => 17, 'id_ps' => 8, 'kode_mk'=>'(2025)MK-2', 'nama_matkul_id' => 'Elektronika Dasar (2025)', 'nama_matkul_en' => 'Basic Electronics (2025)', 'matkul_desc_id' => 'Mempelajari komponen elektronik seperti dioda, transistor, dan op-amp serta aplikasinya. (2025)', 'matkul_desc_en' => 'Studies electronic components such as diodes, transistors, and op-amps and their applications. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 84, 'id_kurikulum' => 17, 'id_ps' => 8, 'kode_mk'=>'(2025)MK-3', 'nama_matkul_id' => 'Sistem Digital (2025)', 'nama_matkul_en' => 'Digital Systems (2025)', 'matkul_desc_id' => 'Logika digital, aljabar Boolean, dan perancangan rangkaian kombinasional dan sekuensial. (2025)', 'matkul_desc_en' => 'Digital logic, Boolean algebra, and the design of combinational and sequential circuits. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 85, 'id_kurikulum' => 17, 'id_ps' => 8, 'kode_mk'=>'(2025)MK-4', 'nama_matkul_id' => 'Mikrokontroler (2025)', 'nama_matkul_en' => 'Microcontrollers (2025)', 'matkul_desc_id' => 'Arsitektur dan pemrograman perangkat mikrokontroler untuk sistem tertanam. (2025)', 'matkul_desc_en' => 'Architecture and programming of microcontroller devices for embedded systems. (2025)', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 86, 'id_kurikulum' => 17, 'id_ps' => 8, 'kode_mk'=>'(2025)MK-5', 'nama_matkul_id' => 'Sistem Kendali (2025)', 'nama_matkul_en' => 'Control Systems (2025)', 'matkul_desc_id' => 'Analisis dan perancangan sistem untuk mengendalikan perilaku sistem dinamis. (2025)', 'matkul_desc_en' => 'Analysis and design of systems to control the behavior of dynamic systems. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'semua' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],

            // Program Studi 9: Teknik Geologi
            ['id_mk' => 87, 'id_kurikulum' => 18, 'id_ps' => 9, 'kode_mk'=>'(2025)MK-1', 'nama_matkul_id' => 'Geologi Fisik (2025)', 'nama_matkul_en' => 'Physical Geology (2025)', 'matkul_desc_id' => 'Mempelajari proses-proses fisik yang membentuk dan mengubah permukaan bumi. (2025)', 'matkul_desc_en' => 'Studies the physical processes that shape and change the Earth\'s surface. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 88, 'id_kurikulum' => 18, 'id_ps' => 9, 'kode_mk'=>'(2025)MK-2', 'nama_matkul_id' => 'Mineralogi (2025)', 'nama_matkul_en' => 'Mineralogy (2025)', 'matkul_desc_id' => 'Studi tentang mineral, termasuk identifikasi, kristalografi, dan sifat fisiknya. (2025)', 'matkul_desc_en' => 'The study of minerals, including their identification, crystallography, and physical properties. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 89, 'id_kurikulum' => 18, 'id_ps' => 9, 'kode_mk'=>'(2025)MK-3', 'nama_matkul_id' => 'Petrologi (2025)', 'nama_matkul_en' => 'Petrology (2025)', 'matkul_desc_id' => 'Studi tentang asal-usul, komposisi, dan klasifikasi batuan. (2025)', 'matkul_desc_en' => 'The study of the origin, composition, and classification of rocks. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 90, 'id_kurikulum' => 18, 'id_ps' => 9, 'kode_mk'=>'(2025)MK-4', 'nama_matkul_id' => 'Struktur Geologi (2025)', 'nama_matkul_en' => 'Structural Geology (2025)', 'matkul_desc_id' => 'Analisis deformasi batuan dan struktur geologi seperti lipatan dan sesar. (2025)', 'matkul_desc_en' => 'Analysis of rock deformation and geological structures such as folds and faults. (2025)', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
            ['id_mk' => 91, 'id_kurikulum' => 18, 'id_ps' => 9, 'kode_mk'=>'(2025)MK-5', 'nama_matkul_id' => 'Geologi Teknik (2025)', 'nama_matkul_en' => 'Engineering Geology (2025)', 'matkul_desc_id' => 'Penerapan prinsip geologi dalam praktik rekayasa, khususnya untuk proyek konstruksi. (2025)', 'matkul_desc_en' => 'Application of geological principles in engineering practice, especially for construction projects. (2025)', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'ganjil' , 'id_pengembang_rps' => null, 'id_koordinator_mk' => null],
 
 
            // untuk percobaan penarikan kita coba di sini
            ['id_mk' => 92, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'HULM1151', 'nama_matkul_id' => 'Bahasa Inggris I', 'nama_matkul_en' => 'English I', 'matkul_desc_id' => 'Pengenalan dasar Bahasa Inggris dalam konteks akademik dan profesional.', 'matkul_desc_en' => 'Basic English introduction in academic and professional contexts.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121 ],
            ['id_mk' => 93, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'HULM1115', 'nama_matkul_id' => 'Pengantar Lingkungan Lahan Basah', 'nama_matkul_en' => 'Introduction to Wetland Environment', 'matkul_desc_id' => 'Memperkenalkan konsep ekosistem lahan basah dan relevansinya terhadap teknologi informasi.', 'matkul_desc_en' => 'Introduction to wetland ecosystems and their relevance to information technology.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121 ],
            ['id_mk' => 94, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI1101', 'nama_matkul_id' => 'Aljabar Linier', 'nama_matkul_en' => 'Linear Algebra', 'matkul_desc_id' => 'Konsep dasar matriks, vektor, dan transformasi linear dalam pemecahan masalah komputasi.', 'matkul_desc_en' => 'Fundamentals of matrices, vectors, and linear transformations in computational problem solving.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121],
            // ['id_mk' => 95, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI1102', 'nama_matkul_id' => 'Kalkulus', 'nama_matkul_en' => 'Calculus', 'matkul_desc_id' => 'Mempelajari konsep limit, turunan, dan integral untuk aplikasi komputasi.', 'matkul_desc_en' => 'Study of limits, derivatives, and integrals for computational applications.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 96, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI1103', 'nama_matkul_id' => 'Berpikir Komputasional', 'nama_matkul_en' => 'Computational Thinking', 'matkul_desc_id' => 'Pengenalan logika berpikir algoritmik dan penyelesaian masalah berbasis komputer.', 'matkul_desc_en' => 'Introduction to algorithmic thinking and computer-based problem solving.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121 ],           
            // ['id_mk' => 97, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI1104', 'nama_matkul_id' => 'Arsitektur dan Organisasi Komputer', 'nama_matkul_en' => 'Computer Architecture and Organization', 'matkul_desc_id' => 'Memahami struktur dan organisasi perangkat keras komputer.', 'matkul_desc_en' => 'Understanding computer hardware structure and organization.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121],
            
             // ['id_mk' => 98, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI1105', 'nama_matkul_id' => 'Pemrograman I', 'nama_matkul_en' => 'Programming I', 'matkul_desc_id' => 'Dasar pemrograman prosedural menggunakan bahasa pemrograman modern.', 'matkul_desc_en' => 'Introduction to procedural programming using modern programming languages.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 1, 'muncul' => 'ganjil', 'id_pengembang_rps' => 127, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 99, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI1206', 'nama_matkul_id' => 'Praktikum Pemrograman I', 'nama_matkul_en' => 'Programming I Practicum', 'matkul_desc_id' => 'Praktik penerapan konsep pemrograman prosedural melalui proyek kecil.', 'matkul_desc_en' => 'Hands-on application of procedural programming through small projects.', 'sks_teori' => 0, 'sks_praktikum' => 1, 'semester' => 1, 'muncul' => 'ganjil', 'id_pengembang_rps' => 128, 'id_koordinator_mk' => 121 ],

            // ['id_mk' => 100, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'HULM1252', 'nama_matkul_id' => 'Bahasa Inggris II', 'nama_matkul_en' => 'English II', 'matkul_desc_id' => 'Melanjutkan Bahasa Inggris I dengan fokus pada komunikasi akademik.', 'matkul_desc_en' => 'Continuation of English I focusing on academic communication.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 101, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI2107', 'nama_matkul_id' => 'Matematika Diskrit', 'nama_matkul_en' => 'Discrete Mathematics', 'matkul_desc_id' => 'Konsep matematika untuk logika, himpunan, graf, dan relasi yang digunakan dalam informatika.', 'matkul_desc_en' => 'Mathematical concepts for logic, sets, graphs, and relations used in informatics.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap', 'id_pengembang_rps' => 122, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 102, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI2108', 'nama_matkul_id' => 'Etika Profesi TI', 'nama_matkul_en' => 'IT Professional Ethics', 'matkul_desc_id' => 'Mempelajari nilai etika dan tanggung jawab profesi di bidang teknologi informasi.', 'matkul_desc_en' => 'Study of ethical values and professional responsibility in information technology.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap', 'id_pengembang_rps' => 123, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 103, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI2109', 'nama_matkul_id' => 'Sistem Operasi', 'nama_matkul_en' => 'Operating Systems', 'matkul_desc_id' => 'Konsep dasar sistem operasi dan manajemen sumber daya komputer.', 'matkul_desc_en' => 'Basic concepts of operating systems and computer resource management.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap', 'id_pengembang_rps' => 124, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 104, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI2110', 'nama_matkul_id' => 'Basis Data I', 'nama_matkul_en' => 'Database I', 'matkul_desc_id' => 'Pengenalan konsep sistem basis data relasional dan SQL.', 'matkul_desc_en' => 'Introduction to relational database systems and SQL.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap', 'id_pengembang_rps' => 125, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 105, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI2211', 'nama_matkul_id' => 'Praktikum Basis Data I', 'nama_matkul_en' => 'Database I Practicum', 'matkul_desc_id' => 'Latihan implementasi sistem basis data menggunakan SQL.', 'matkul_desc_en' => 'Implementation exercises of database systems using SQL.', 'sks_teori' => 0, 'sks_praktikum' => 1, 'semester' => 2, 'muncul' => 'genap', 'id_pengembang_rps' => 126, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 106, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI2112', 'nama_matkul_id' => 'Pemrograman Web I', 'nama_matkul_en' => 'Web Programming I', 'matkul_desc_id' => 'Pengenalan konsep dasar pengembangan web dan HTML, CSS, serta JavaScript.', 'matkul_desc_en' => 'Introduction to basic web development concepts and HTML, CSS, and JavaScript.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 2, 'muncul' => 'genap', 'id_pengembang_rps' => 127, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 107, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI2213', 'nama_matkul_id' => 'Praktikum Pemrograman Web I', 'nama_matkul_en' => 'Web Programming I Practicum', 'matkul_desc_id' => 'Praktik pembuatan halaman web interaktif menggunakan HTML, CSS, dan JavaScript.', 'matkul_desc_en' => 'Hands-on practice in creating interactive web pages using HTML, CSS, and JavaScript.', 'sks_teori' => 0, 'sks_praktikum' => 1, 'semester' => 2, 'muncul' => 'genap', 'id_pengembang_rps' => 128, 'id_koordinator_mk' => 121 ],

            // ['id_mk' => 108, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI2114', 'nama_matkul_id' => 'Algoritma dan Struktur Data', 'nama_matkul_en' => 'Algorithms and Data Structures', 'matkul_desc_id' => 'Dasar-dasar analisis algoritma, struktur data linear dan non-linear, serta teknik penyelesaian masalah.', 'matkul_desc_en' => 'Fundamentals of algorithm analysis, linear and non-linear data structures, and problem-solving techniques.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 109, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI2215', 'nama_matkul_id' => 'Praktikum Algoritma dan Struktur Data', 'nama_matkul_en' => 'Algorithms and Data Structures Practicum', 'matkul_desc_id' => 'Latihan penerapan struktur data dan algoritma melalui tugas pemrograman.', 'matkul_desc_en' => 'Practical exercises implementing data structures and algorithms through programming assignments.', 'sks_teori' => 0, 'sks_praktikum' => 1, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 122, 'id_koordinator_mk' => 121],
            // ['id_mk' => 110, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI3116', 'nama_matkul_id' => 'Statistika dan Probabilitas', 'nama_matkul_en' => 'Statistics and Probability', 'matkul_desc_id' => 'Statistika dasar dan probabilitas untuk aplikasi data dan ilmu komputer.', 'matkul_desc_en' => 'Basic statistics and probability for data applications and computer science.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 123, 'id_koordinator_mk' => 121 ],
            // [ 'id_mk' => 111,'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI3117', 'nama_matkul_id' => 'Interaksi Manusia Komputer', 'nama_matkul_en' => 'Human-Computer Interaction', 'matkul_desc_id' => 'Prinsip dasar desain antarmuka, evaluasi kegunaan, dan prototyping.', 'matkul_desc_en' => 'Fundamentals of interface design, usability evaluation, and prototyping.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 124, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 112, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI3118', 'nama_matkul_id' => 'Geoinformatika', 'nama_matkul_en' => 'Geoinformatics', 'matkul_desc_id' => 'Pengantar sistem informasi geografis dan pemrosesan data spasial.', 'matkul_desc_en' => 'Introduction to geographic information systems and spatial data processing.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 125, 'id_koordinator_mk' => 121],
            // ['id_mk' => 113, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI3119', 'nama_matkul_id' => 'Analisis dan Perancangan Sistem', 'nama_matkul_en' => 'Systems Analysis and Design', 'matkul_desc_id' => 'Metode analisis kebutuhan, perancangan sistem, UML, dan dokumentasi.', 'matkul_desc_en' => 'Requirements analysis methods, system design, UML, and documentation.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 126, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 114, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI3120', 'nama_matkul_id' => 'Jaringan Komputer dan Komunikasi Data', 'nama_matkul_en' => 'Computer Networks and Data Communication', 'matkul_desc_id' => 'Konsep jaringan, protokol, dan komunikasi data.', 'matkul_desc_en' => 'Network concepts, protocols, and data communication fundamentals.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 127, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 115, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI3221', 'nama_matkul_id' => 'Praktikum Jaringan Komputer dan Komunikasi Data', 'nama_matkul_en' => 'Computer Networks Practicum', 'matkul_desc_id' => 'Praktik konfigurasi jaringan dan analisis trafik.', 'matkul_desc_en' => 'Hands-on network configuration and traffic analysis.', 'sks_teori' => 0, 'sks_praktikum' => 1, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 128, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 116, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI3122', 'nama_matkul_id' => 'Pemrograman II', 'nama_matkul_en' => 'Programming II', 'matkul_desc_id' => 'Lanjutan pemrograman: konsep OOP, struktur program, dan desain modul.', 'matkul_desc_en' => 'Advanced programming: OOP concepts, program structure, and module design.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 117, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI3223', 'nama_matkul_id' => 'Praktikum Pemrograman II', 'nama_matkul_en' => 'Programming II Practicum', 'matkul_desc_id' => 'Latihan implementasi konsep pemrograman lanjutan dan OOP.', 'matkul_desc_en' => 'Practical exercises in advanced programming and OOP implementation.', 'sks_teori' => 0, 'sks_praktikum' => 1, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 122, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 118, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI3124', 'nama_matkul_id' => 'Basis Data II', 'nama_matkul_en' => 'Database II', 'matkul_desc_id' => 'Topik lanjutan basis data: normalisasi, indexing, dan performa query.', 'matkul_desc_en' => 'Advanced database topics: normalization, indexing, and query performance.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 123, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 119, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI3225', 'nama_matkul_id' => 'Praktikum Basis Data II', 'nama_matkul_en' => 'Database II Practicum', 'matkul_desc_id' => 'Latihan lanjutan penggunaan DBMS dan optimasi query.', 'matkul_desc_en' => 'Advanced DBMS exercises and query optimization.', 'sks_teori' => 0, 'sks_praktikum' => 1, 'semester' => 3, 'muncul' => 'ganjil', 'id_pengembang_rps' => 124, 'id_koordinator_mk' => 121],

            // ['id_mk' => 120, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'HULM1251', 'nama_matkul_id' => 'Kewirausahaan', 'nama_matkul_en' => 'Entrepreneurship', 'matkul_desc_id' => 'Prinsip dasar kewirausahaan dan penerapan bisnis berbasis teknologi.', 'matkul_desc_en' => 'Basic entrepreneurship principles and application of tech-based businesses.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap', 'id_pengembang_rps' => 125, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 121, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI4126', 'nama_matkul_id' => 'Keterampilan Berkomunikasi', 'nama_matkul_en' => 'Communication Skills', 'matkul_desc_id' => 'Pengembangan kemampuan komunikasi lisan dan tulisan dalam konteks profesional TI.', 'matkul_desc_en' => 'Development of oral and written communication skills in IT professional contexts.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap', 'id_pengembang_rps' => 126, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 122, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI4127', 'nama_matkul_id' => 'Administrasi Sistem dan Jaringan', 'nama_matkul_en' => 'System and Network Administration', 'matkul_desc_id' => 'Manajemen sistem operasi server, pelayanan jaringan, dan administrasi infrastruktur.', 'matkul_desc_en' => 'Server OS management, network services, and infrastructure administration.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap', 'id_pengembang_rps' => 127, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 123, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI4128', 'nama_matkul_id' => 'Keamanan Siber', 'nama_matkul_en' => 'Cybersecurity', 'matkul_desc_id' => 'Prinsip keamanan informasi, ancaman, dan teknik mitigasi.', 'matkul_desc_en' => 'Information security principles, threats, and mitigation techniques.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap', 'id_pengembang_rps' => 128, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 124, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI4129', 'nama_matkul_id' => 'Rekayasa Perangkat Lunak', 'nama_matkul_en' => 'Software Engineering', 'matkul_desc_id' => 'Metodologi rekayasa perangkat lunak, lifecycle, dan praktik terbaik pengembangan.', 'matkul_desc_en' => 'Software engineering methodologies, lifecycle, and best development practices.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 125, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI4130', 'nama_matkul_id' => 'Pemrograman Mobile', 'nama_matkul_en' => 'Mobile Programming', 'matkul_desc_id' => 'Pengembangan aplikasi mobile menggunakan framework modern.', 'matkul_desc_en' => 'Developing mobile applications using modern frameworks.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap', 'id_pengembang_rps' => 122, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 126, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI4231', 'nama_matkul_id' => 'Praktikum Pemrograman Mobile', 'nama_matkul_en' => 'Mobile Programming Practicum', 'matkul_desc_id' => 'Praktik pengembangan aplikasi mobile berbasis proyek.', 'matkul_desc_en' => 'Project-based mobile app development practice.', 'sks_teori' => 0, 'sks_praktikum' => 1, 'semester' => 4, 'muncul' => 'genap', 'id_pengembang_rps' => 123, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 127, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI4132', 'nama_matkul_id' => 'Pemrograman Web II', 'nama_matkul_en' => 'Web Programming II', 'matkul_desc_id' => 'Pengembangan web dinamis, backend dasar, dan integrasi API.', 'matkul_desc_en' => 'Dynamic web development, basic backend, and API integration.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 4, 'muncul' => 'genap', 'id_pengembang_rps' => 124, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 128, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI4233', 'nama_matkul_id' => 'Praktikum Pemrograman Web II', 'nama_matkul_en' => 'Web Programming II Practicum', 'matkul_desc_id' => 'Latihan pembuatan aplikasi web dengan backend sederhana dan koneksi database.', 'matkul_desc_en' => 'Hands-on building of web applications with simple backends and database connectivity.', 'sks_teori' => 0, 'sks_praktikum' => 1, 'semester' => 4, 'muncul' => 'genap', 'id_pengembang_rps' => 125, 'id_koordinator_mk' => 121 ],

            // ['id_mk' => 129, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'HULM1171', 'nama_matkul_id' => 'Pancasila', 'nama_matkul_en' => 'Pancasila', 'matkul_desc_id' => 'Kajian Pancasila sebagai dasar negara dan implementasinya dalam kehidupan berbangsa.', 'matkul_desc_en' => 'Study of Pancasila as the state ideology and its implementation in national life.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'ganjil', 'id_pengembang_rps' => 126, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 130, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI5134', 'nama_matkul_id' => 'Layanan dan Sistem Virtual', 'nama_matkul_en' => 'Virtual Services and Systems', 'matkul_desc_id' => 'Konsep virtualisasi, cloud dasar, dan layanan TI virtual.', 'matkul_desc_en' => 'Virtualization concepts, basic cloud, and virtual IT services.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'ganjil', 'id_pengembang_rps' => 127, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 131, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI5135', 'nama_matkul_id' => 'Kecerdasan Bisnis', 'nama_matkul_en' => 'Business Intelligence', 'matkul_desc_id' => 'Konsep pengolahan data bisnis, ETL, dan dashboard untuk pengambilan keputusan.', 'matkul_desc_en' => 'Business data processing, ETL, and dashboards for decision making.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'ganjil', 'id_pengembang_rps' => 128, 'id_koordinator_mk' => 121],
            // ['id_mk' => 132, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI5136', 'nama_matkul_id' => 'Manajemen Proyek TI', 'nama_matkul_en' => 'IT Project Management', 'matkul_desc_id' => 'Prinsip manajemen proyek, perencanaan, dan pengelolaan tim TI.', 'matkul_desc_en' => 'Project management principles, planning, and IT team management.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 133, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI5137', 'nama_matkul_id' => 'Metodologi Penelitian', 'nama_matkul_en' => 'Research Methodology', 'matkul_desc_id' => 'Metode penelitian ilmiah, pengumpulan data, dan penulisan laporan penelitian.', 'matkul_desc_en' => 'Scientific research methods, data collection, and report writing.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 5, 'muncul' => 'ganjil', 'id_pengembang_rps' => 122, 'id_koordinator_mk' => 121 ],
          
            // ['id_mk' => 134, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'HULM1152', 'nama_matkul_id' => 'Bahasa Indonesia', 'nama_matkul_en' => 'Indonesian Language', 'matkul_desc_id' => 'Kemampuan berbahasa Indonesia lisan dan tulisan sesuai standar akademik.', 'matkul_desc_en' => 'Proficiency in Indonesian language for academic oral and written contexts.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 6, 'muncul' => 'genap', 'id_pengembang_rps' => 125, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 135, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'HULM1272', 'nama_matkul_id' => 'Kewarganegaraan', 'nama_matkul_en' => 'Civics', 'matkul_desc_id' => 'Pembelajaran hak dan kewajiban warga negara serta sistem pemerintahan.', 'matkul_desc_en' => 'Study of citizen rights and obligations and systems of governance.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 6, 'muncul' => 'genap', 'id_pengembang_rps' => 126, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 136, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI6138', 'nama_matkul_id' => 'Komputasi Awan', 'nama_matkul_en' => 'Cloud Computing', 'matkul_desc_id' => 'Konsep dan layanan komputasi awan serta penerapannya pada infrastruktur TI.', 'matkul_desc_en' => 'Cloud computing concepts and services and their application in IT infrastructure.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 6, 'muncul' => 'genap', 'id_pengembang_rps' => 127, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 137, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI6139', 'nama_matkul_id' => 'Integrasi Sistem', 'nama_matkul_en' => 'Systems Integration', 'matkul_desc_id' => 'Teknik integrasi sistem, API orchestration, dan middleware.', 'matkul_desc_en' => 'System integration techniques, API orchestration, and middleware.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 6, 'muncul' => 'genap', 'id_pengembang_rps' => 128, 'id_koordinator_mk' => 121],
            // ['id_mk' => 138, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI6140', 'nama_matkul_id' => 'Pengujian dan Penjaminan Kualitas Perangkat Lunak', 'nama_matkul_en' => 'Software Testing and Quality Assurance', 'matkul_desc_id' => 'Metode pengujian perangkat lunak, CI/CD, dan jaminan kualitas.', 'matkul_desc_en' => 'Software testing methods, CI/CD, and quality assurance.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 6, 'muncul' => 'genap', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 139, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI6141', 'nama_matkul_id' => 'Desain Pengalaman Pengguna', 'nama_matkul_en' => 'User Experience Design', 'matkul_desc_id' => 'Prinsip UX, riset pengguna, dan pembuatan prototype interaktif.', 'matkul_desc_en' => 'UX principles, user research, and creating interactive prototypes.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 6, 'muncul' => 'genap', 'id_pengembang_rps' => 122, 'id_koordinator_mk' => 121 ],
            // [ 'id_mk' => 140,'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'KONS3', 'nama_matkul_id' => 'Mata Kuliah Konsentrasi III', 'nama_matkul_en' => 'Concentration Course III', 'matkul_desc_id' => 'Mata kuliah konsentrasi (pilihan) sesuai jalur spesialisasi.', 'matkul_desc_en' => 'Concentration elective course according to student specialization.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 6, 'muncul' => 'genap', 'id_pengembang_rps' => 123, 'id_koordinator_mk' => 121 ],

            // ['id_mk' => 141, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'HULM1161', 'nama_matkul_id' => 'Agama', 'nama_matkul_en' => 'Religious Studies', 'matkul_desc_id' => 'Mata kuliah agama sesuai peminatan dan tata nilai keagamaan.', 'matkul_desc_en' => 'Religious studies according to specialization and religious values.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 124, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 142, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI7142', 'nama_matkul_id' => 'Praktik Kerja Lapangan', 'nama_matkul_en' => 'Field Work Practice', 'matkul_desc_id' => 'Magang/praktik kerja lapangan untuk pengalaman industri.', 'matkul_desc_en' => 'Internship/field work for industry experience.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 125, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 143, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI7143', 'nama_matkul_id' => 'Pra Skripsi', 'nama_matkul_en' => 'Pre-Thesis', 'matkul_desc_id' => 'Persiapan penyusunan tugas akhir dan proposal penelitian.', 'matkul_desc_en' => 'Preparation for final project and research proposal writing.', 'sks_teori' => 2, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 126, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 144, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'KONS4', 'nama_matkul_id' => 'Mata Kuliah Konsentrasi IV', 'nama_matkul_en' => 'Concentration Course IV', 'matkul_desc_id' => 'Mata kuliah konsentrasi (pilihan) sesuai jalur spesialisasi.', 'matkul_desc_en' => 'Concentration elective course according to student specialization.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 127, 'id_koordinator_mk' => 121],
            // ['id_mk' => 145, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'KONS5', 'nama_matkul_id' => 'Mata Kuliah Konsentrasi V', 'nama_matkul_en' => 'Concentration Course V', 'matkul_desc_id' => 'Mata kuliah konsentrasi (pilihan) sesuai jalur spesialisasi.', 'matkul_desc_en' => 'Concentration elective course according to student specialization.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 128, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 146, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'PIL1', 'nama_matkul_id' => 'Mata Kuliah Pilihan I', 'nama_matkul_en' => 'Elective Course I', 'matkul_desc_id' => 'Mata kuliah pilihan untuk pemenuhan sks sesuai kurikulum.', 'matkul_desc_en' => 'Elective course to fulfill curriculum credit requirements.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121 ],

            // ['id_mk' => 147, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI8144', 'nama_matkul_id' => 'Skripsi', 'nama_matkul_en' => 'Thesis', 'matkul_desc_id' => 'Penyusunan tugas akhir berupa skripsi yang menunjukkan kompetensi lulusan.', 'matkul_desc_en' => 'Final project (thesis) demonstrating graduate competencies.', 'sks_teori' => 6, 'sks_praktikum' => 0, 'semester' => 8, 'muncul' => 'genap', 'id_pengembang_rps' => 122, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 148, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'PIL2', 'nama_matkul_id' => 'Mata Kuliah Pilihan II', 'nama_matkul_en' => 'Elective Course II', 'matkul_desc_id' => 'Mata kuliah pilihan untuk pemenuhan sks akhir.', 'matkul_desc_en' => 'Elective course for final semester credit fulfillment.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 8, 'muncul' => 'genap', 'id_pengembang_rps' => 123, 'id_koordinator_mk' => 121 ],
 
            // ['id_mk' => 149, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI7355', 'nama_matkul_id' => 'Jaringan Nirkabel', 'nama_matkul_en' => 'Wireless Networks', 'matkul_desc_id' => 'Studi jaringan nirkabel, protokol, dan aplikasinya.', 'matkul_desc_en' => 'Study of wireless networks, protocols, and applications.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 125, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 150, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI7356', 'nama_matkul_id' => 'Pengembangan Aplikasi Game', 'nama_matkul_en' => 'Game Application Development', 'matkul_desc_id' => 'Desain dan pengembangan aplikasi/game interaktif.', 'matkul_desc_en' => 'Design and development of interactive applications/games.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 126, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 151, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI7357', 'nama_matkul_id' => 'Pengolahan Citra Digital', 'nama_matkul_en' => 'Digital Image Processing', 'matkul_desc_id' => 'Dasar pemrosesan citra, filtering, dan ekstraksi fitur.', 'matkul_desc_en' => 'Basics of image processing, filtering, and feature extraction.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 127, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 152, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI8358', 'nama_matkul_id' => 'Blockchain', 'nama_matkul_en' => 'Blockchain', 'matkul_desc_id' => 'Prinsip blockchain, smart contract, dan aplikasinya.', 'matkul_desc_en' => 'Blockchain principles, smart contracts, and applications.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 128, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 153, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI8359', 'nama_matkul_id' => 'Augmented dan Virtual Reality', 'nama_matkul_en' => 'Augmented and Virtual Reality', 'matkul_desc_id' => 'Teknologi AR/VR dan penerapannya dalam antarmuka interaktif.', 'matkul_desc_en' => 'AR/VR technologies and their application in interactive interfaces.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121],
            // ['id_mk' => 154, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI8360', 'nama_matkul_id' => 'Sistem Tertanam', 'nama_matkul_en' => 'Embedded Systems', 'matkul_desc_id' => 'Konsep sistem tertanam dan pemrograman perangkat keras terbenam.', 'matkul_desc_en' => 'Embedded systems concepts and programming of embedded hardware.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 122, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 155, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI5550', 'nama_matkul_id' => 'Data Analitik', 'nama_matkul_en' => 'Data Analytics', 'matkul_desc_id' => 'Metode analisis data untuk mendukung pengambilan keputusan.', 'matkul_desc_en' => 'Data analysis methods to support decision making.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 6, 'muncul' => 'genap', 'id_pengembang_rps' => 123, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 156, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI5551', 'nama_matkul_id' => 'Visualisasi Data', 'nama_matkul_en' => 'Data Visualization', 'matkul_desc_id' => 'Teknik visualisasi data dan pembuatan dashboard informatif.', 'matkul_desc_en' => 'Data visualization techniques and creating informative dashboards.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 6, 'muncul' => 'genap', 'id_pengembang_rps' => 124, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 157, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI6552', 'nama_matkul_id' => 'Pembelajaran Mesin I', 'nama_matkul_en' => 'Machine Learning I', 'matkul_desc_id' => 'Pengenalan pembelajaran mesin: supervised learning, dasar algoritma, dan evaluasi.', 'matkul_desc_en' => 'Introduction to machine learning: supervised learning, basic algorithms, and evaluation.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 6, 'muncul' => 'genap', 'id_pengembang_rps' => 125, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 158, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI7553', 'nama_matkul_id' => 'Internet of Things', 'nama_matkul_en' => 'Internet of Things', 'matkul_desc_id' => 'Dasar-dasar IoT, arsitektur, dan penerapan pada sistem terdistribusi.', 'matkul_desc_en' => 'IoT fundamentals, architecture, and applications in distributed systems.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 6, 'muncul' => 'genap', 'id_pengembang_rps' => 126, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 159, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI7554', 'nama_matkul_id' => 'Pembelajaran Mesin II', 'nama_matkul_en' => 'Machine Learning II', 'matkul_desc_id' => 'Lanjutan topik pembelajaran mesin, deep learning dasar, dan penerapan praktis.', 'matkul_desc_en' => 'Advanced machine learning topics, basic deep learning, and practical applications.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 6, 'muncul' => 'genap', 'id_pengembang_rps' => 127, 'id_koordinator_mk' => 121 ],

            // ['id_mk' => 160, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI5445', 'nama_matkul_id' => 'Manajemen Layanan Teknologi Informasi', 'nama_matkul_en' => 'IT Service Management', 'matkul_desc_id' => 'Prinsip manajemen layanan TI, ITIL dasar, dan praktik operasi layanan.', 'matkul_desc_en' => 'IT service management principles, basic ITIL, and service operations practices.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 128, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 161, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI5446', 'nama_matkul_id' => 'Manajemen Resiko Teknologi Informasi', 'nama_matkul_en' => 'IT Risk Management', 'matkul_desc_id' => 'Identifikasi dan mitigasi risiko pada proyek TI dan infrastruktur.', 'matkul_desc_en' => 'Identification and mitigation of risks in IT projects and infrastructure.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 121, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 162, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI6447', 'nama_matkul_id' => 'Arsitektur Enterprise', 'nama_matkul_en' => 'Enterprise Architecture', 'matkul_desc_id' => 'Konsep arsitektur perusahaan dan integrasi sistem skala besar.', 'matkul_desc_en' => 'Enterprise architecture concepts and large-scale system integration.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 122, 'id_koordinator_mk' => 121],
            // ['id_mk' => 163, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI7448', 'nama_matkul_id' => 'Manajemen Keamanan Informasi', 'nama_matkul_en' => 'Information Security Management', 'matkul_desc_id' => 'Manajemen keamanan informasi pada organisasi, kebijakan, dan kontrol.', 'matkul_desc_en' => 'Information security management in organizations: policies and controls.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 123, 'id_koordinator_mk' => 121 ],
            // ['id_mk' => 164, 'id_kurikulum' => 7, 'id_ps' => 7, 'kode_mk'=>'STI7449', 'nama_matkul_id' => 'Audit Teknologi Informasi', 'nama_matkul_en' => 'IT Audit', 'matkul_desc_id' => 'Prinsip audit sistem informasi dan tata kelola TI.', 'matkul_desc_en' => 'Information systems audit principles and IT governance.', 'sks_teori' => 3, 'sks_praktikum' => 0, 'semester' => 7, 'muncul' => 'ganjil', 'id_pengembang_rps' => 124, 'id_koordinator_mk' => 121 ],
        ]);
    }
}