<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MataKuliahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mata_kuliah')->insert([
            // Program Studi 1: Teknik Sipil
            ['id_mk' => 1, 'id_ps' => 1, 'nama_matkul_id' => 'Mekanika Teknik', 'nama_matkul_en' => 'Engineering Mechanics', 'matkul_desc_id' => 'Mempelajari keseimbangan dan gerak benda padat serta aplikasinya dalam rekayasa.', 'matkul_desc_en' => 'Studies the equilibrium and motion of solid bodies and their application in engineering.', 'jumlah_sks' => 3, 'semester' => 1],
            ['id_mk' => 2, 'id_ps' => 1, 'nama_matkul_id' => 'Struktur Beton', 'nama_matkul_en' => 'Concrete Structures', 'matkul_desc_id' => 'Analisis dan perancangan elemen-elemen struktur beton bertulang.', 'matkul_desc_en' => 'Analysis and design of reinforced concrete structural elements.', 'jumlah_sks' => 3, 'semester' => 2],
            ['id_mk' => 3, 'id_ps' => 1, 'nama_matkul_id' => 'Hidrolika', 'nama_matkul_en' => 'Hydraulics', 'matkul_desc_id' => 'Studi tentang sifat-sifat mekanis fluida dan aplikasinya dalam sistem aliran.', 'matkul_desc_en' => 'Study of the mechanical properties of fluids and their application in flow systems.', 'jumlah_sks' => 2, 'semester' => 3],
            ['id_mk' => 4, 'id_ps' => 1, 'nama_matkul_id' => 'Manajemen Konstruksi', 'nama_matkul_en' => 'Construction Management', 'matkul_desc_id' => 'Prinsip-prinsip perencanaan, pengorganisasian, dan pengendalian proyek konstruksi.', 'matkul_desc_en' => 'Principles of planning, organizing, and controlling construction projects.', 'jumlah_sks' => 3, 'semester' => 4],
            ['id_mk' => 5, 'id_ps' => 1, 'nama_matkul_id' => 'Geoteknik', 'nama_matkul_en' => 'Geotechnics', 'matkul_desc_id' => 'Mempelajari perilaku tanah dan batuan serta interaksinya dengan struktur rekayasa.', 'matkul_desc_en' => 'Studies the behavior of soil and rock and their interaction with engineering structures.', 'jumlah_sks' => 3, 'semester' => 5],

            // Program Studi 2: Teknik Pertambangan
            ['id_mk' => 6, 'id_ps' => 2, 'nama_matkul_id' => 'Geologi Dasar', 'nama_matkul_en' => 'Basic Geology', 'matkul_desc_id' => 'Pengenalan tentang material bumi, proses geologi, dan struktur kerak bumi.', 'matkul_desc_en' => 'Introduction to earth materials, geological processes, and the structure of the Earth\'s crust.', 'jumlah_sks' => 3, 'semester' => 1],
            ['id_mk' => 7, 'id_ps' => 2, 'nama_matkul_id' => 'Eksplorasi Tambang', 'nama_matkul_en' => 'Mining Exploration', 'matkul_desc_id' => 'Metode pencarian dan penemuan deposit mineral yang bernilai ekonomis.', 'matkul_desc_en' => 'Methods of searching for and discovering economically valuable mineral deposits.', 'jumlah_sks' => 3, 'semester' => 2],
            ['id_mk' => 8, 'id_ps' => 2, 'nama_matkul_id' => 'Penambangan Permukaan', 'nama_matkul_en' => 'Surface Mining', 'matkul_desc_id' => 'Teknik dan metode penambangan yang dilakukan di permukaan bumi.', 'matkul_desc_en' => 'Techniques and methods of mining conducted on the Earth\'s surface.', 'jumlah_sks' => 3, 'semester' => 3],
            ['id_mk' => 9, 'id_ps' => 2, 'nama_matkul_id' => 'Ventilasi Tambang', 'nama_matkul_en' => 'Mine Ventilation', 'matkul_desc_id' => 'Pengendalian aliran udara di dalam tambang bawah tanah untuk menyediakan lingkungan kerja yang aman.', 'matkul_desc_en' => 'Control of airflow within underground mines to provide a safe working environment.', 'jumlah_sks' => 2, 'semester' => 4],
            ['id_mk' => 10, 'id_ps' => 2, 'nama_matkul_id' => 'Evaluasi Cadangan', 'nama_matkul_en' => 'Reserve Evaluation', 'matkul_desc_id' => 'Penilaian kuantitas dan kualitas cadangan mineral untuk menentukan kelayakan tambang.', 'matkul_desc_en' => 'Assessment of the quantity and quality of mineral reserves to determine mine feasibility.', 'jumlah_sks' => 3, 'semester' => 5],

            // Program Studi 3: Teknik Mesin
            ['id_mk' => 11, 'id_ps' => 3, 'nama_matkul_id' => 'Termodinamika', 'nama_matkul_en' => 'Thermodynamics', 'matkul_desc_id' => 'Studi tentang hubungan antara panas, kerja, dan energi dalam sistem fisik.', 'matkul_desc_en' => 'Study of the relationship between heat, work, and energy in physical systems.', 'jumlah_sks' => 3, 'semester' => 1],
            ['id_mk' => 12, 'id_ps' => 3, 'nama_matkul_id' => 'Mekanika Fluida', 'nama_matkul_en' => 'Fluid Mechanics', 'matkul_desc_id' => 'Mempelajari perilaku fluida (cair dan gas) dalam keadaan diam dan bergerak.', 'matkul_desc_en' => 'Studies the behavior of fluids (liquids and gases) at rest and in motion.', 'jumlah_sks' => 3, 'semester' => 2],
            ['id_mk' => 13, 'id_ps' => 3, 'nama_matkul_id' => 'Konversi Energi', 'nama_matkul_en' => 'Energy Conversion', 'matkul_desc_id' => 'Proses perubahan energi dari satu bentuk ke bentuk lain, seperti dari panas ke mekanik.', 'matkul_desc_en' => 'The process of changing energy from one form to another, such as from heat to mechanical.', 'jumlah_sks' => 3, 'semester' => 3],
            ['id_mk' => 14, 'id_ps' => 3, 'nama_matkul_id' => 'Perpindahan Panas', 'nama_matkul_en' => 'Heat Transfer', 'matkul_desc_id' => 'Mekanisme perpindahan energi termal melalui konduksi, konveksi, dan radiasi.', 'matkul_desc_en' => 'Mechanisms of thermal energy transfer through conduction, convection, and radiation.', 'jumlah_sks' => 2, 'semester' => 4],
            ['id_mk' => 15, 'id_ps' => 3, 'nama_matkul_id' => 'Desain Mesin', 'nama_matkul_en' => 'Machine Design', 'matkul_desc_id' => 'Penerapan prinsip-prinsip rekayasa untuk merancang komponen dan sistem mesin.', 'matkul_desc_en' => 'Application of engineering principles to design machine components and systems.', 'jumlah_sks' => 3, 'semester' => 5],

            // Program Studi 4: Teknik Lingkungan
            ['id_mk' => 16, 'id_ps' => 4, 'nama_matkul_id' => 'Kimia Lingkungan', 'nama_matkul_en' => 'Environmental Chemistry', 'matkul_desc_id' => 'Studi tentang proses kimia yang terjadi di lingkungan alam (udara, air, tanah).', 'matkul_desc_en' => 'Study of chemical processes that occur in the natural environment (air, water, soil).', 'jumlah_sks' => 3, 'semester' => 1],
            ['id_mk' => 17, 'id_ps' => 4, 'nama_matkul_id' => 'Teknologi Air Bersih', 'nama_matkul_en' => 'Clean Water Technology', 'matkul_desc_id' => 'Metode pengolahan air untuk menghasilkan air yang aman untuk dikonsumsi.', 'matkul_desc_en' => 'Water treatment methods to produce water that is safe for consumption.', 'jumlah_sks' => 3, 'semester' => 2],
            ['id_mk' => 18, 'id_ps' => 4, 'nama_matkul_id' => 'Pengelolaan Limbah', 'nama_matkul_en' => 'Waste Management', 'matkul_desc_id' => 'Prinsip dan praktik pengumpulan, pengolahan, dan pembuangan limbah padat dan cair.', 'matkul_desc_en' => 'Principles and practices of collecting, treating, and disposing of solid and liquid waste.', 'jumlah_sks' => 3, 'semester' => 3],
            ['id_mk' => 19, 'id_ps' => 4, 'nama_matkul_id' => 'EKL dan AMDAL', 'nama_matkul_en' => 'EKL and AMDAL', 'matkul_desc_id' => 'Studi mengenai evaluasi dampak lingkungan dari suatu proyek atau kegiatan.', 'matkul_desc_en' => 'Study concerning the environmental impact assessment of a project or activity.', 'jumlah_sks' => 2, 'semester' => 4],
            ['id_mk' => 20, 'id_ps' => 4, 'nama_matkul_id' => 'Teknologi Lingkungan', 'nama_matkul_en' => 'Environmental Technology', 'matkul_desc_id' => 'Penerapan ilmu pengetahuan dan rekayasa untuk melindungi dan memulihkan lingkungan.', 'matkul_desc_en' => 'Application of science and engineering to protect and restore the environment.', 'jumlah_sks' => 3, 'semester' => 5],

            // Program Studi 5: Arsitektur
            ['id_mk' => 21, 'id_ps' => 5, 'nama_matkul_id' => 'Dasar Desain Arsitektur', 'nama_matkul_en' => 'Fundamentals of Architectural Design', 'matkul_desc_id' => 'Pengenalan prinsip-prinsip dasar dalam perancangan ruang dan bentuk arsitektur.', 'matkul_desc_en' => 'Introduction to the basic principles in the design of architectural space and form.', 'jumlah_sks' => 3, 'semester' => 1],
            ['id_mk' => 22, 'id_ps' => 5, 'nama_matkul_id' => 'Arsitektur Vernakular', 'nama_matkul_en' => 'Vernacular Architecture', 'matkul_desc_id' => 'Studi tentang arsitektur tradisional yang tumbuh dari budaya dan material lokal.', 'matkul_desc_en' => 'Study of traditional architecture that grows from local culture and materials.', 'jumlah_sks' => 3, 'semester' => 2],
            ['id_mk' => 23, 'id_ps' => 5, 'nama_matkul_id' => 'Teknologi Bangunan', 'nama_matkul_en' => 'Building Technology', 'matkul_desc_id' => 'Mempelajari material, struktur, dan sistem konstruksi dalam bangunan.', 'matkul_desc_en' => 'Studies materials, structures, and construction systems in buildings.', 'jumlah_sks' => 3, 'semester' => 3],
            ['id_mk' => 24, 'id_ps' => 5, 'nama_matkul_id' => 'Perancangan Kota', 'nama_matkul_en' => 'Urban Design', 'matkul_desc_id' => 'Proses merancang dan membentuk fitur fisik kota atau perkotaan.', 'matkul_desc_en' => 'The process of designing and shaping the physical features of cities or urban areas.', 'jumlah_sks' => 2, 'semester' => 4],
            ['id_mk' => 25, 'id_ps' => 5, 'nama_matkul_id' => 'Manajemen Proyek Arsitektur', 'nama_matkul_en' => 'Architectural Project Management', 'matkul_desc_id' => 'Pengelolaan proyek arsitektur dari tahap konsep hingga penyelesaian konstruksi.', 'matkul_desc_en' => 'Management of architectural projects from the concept stage to construction completion.', 'jumlah_sks' => 3, 'semester' => 5],

            // Program Studi 6: Teknik Kimia
            ['id_mk' => 26, 'id_ps' => 6, 'nama_matkul_id' => 'Kimia Dasar', 'nama_matkul_en' => 'Basic Chemistry', 'matkul_desc_id' => 'Konsep fundamental kimia, termasuk struktur atom, ikatan kimia, dan stoikiometri.', 'matkul_desc_en' => 'Fundamental concepts of chemistry, including atomic structure, chemical bonding, and stoichiometry.', 'jumlah_sks' => 3, 'semester' => 1],
            ['id_mk' => 27, 'id_ps' => 6, 'nama_matkul_id' => 'Perpindahan Massa', 'nama_matkul_en' => 'Mass Transfer', 'matkul_desc_id' => 'Perpindahan komponen kimia antara fasa yang berbeda, seperti dalam distilasi atau absorpsi.', 'matkul_desc_en' => 'The movement of chemical components between different phases, such as in distillation or absorption.', 'jumlah_sks' => 3, 'semester' => 2],
            ['id_mk' => 28, 'id_ps' => 6, 'nama_matkul_id' => 'Rekayasa Reaksi Kimia', 'nama_matkul_en' => 'Chemical Reaction Engineering', 'matkul_desc_id' => 'Perancangan dan operasi reaktor kimia untuk produksi skala industri.', 'matkul_desc_en' => 'Design and operation of chemical reactors for industrial-scale production.', 'jumlah_sks' => 3, 'semester' => 3],
            ['id_mk' => 29, 'id_ps' => 6, 'nama_matkul_id' => 'Instrumentasi Proses', 'nama_matkul_en' => 'Process Instrumentation', 'matkul_desc_id' => 'Pengukuran dan pengendalian variabel proses seperti suhu, tekanan, dan laju alir.', 'matkul_desc_en' => 'Measurement and control of process variables such as temperature, pressure, and flow rate.', 'jumlah_sks' => 2, 'semester' => 4],
            ['id_mk' => 30, 'id_ps' => 6, 'nama_matkul_id' => 'Manajemen Industri Kimia', 'nama_matkul_en' => 'Chemical Industry Management', 'matkul_desc_id' => 'Aspek bisnis dan manajemen dalam operasi industri kimia.', 'matkul_desc_en' => 'Business and management aspects in the operation of the chemical industry.', 'jumlah_sks' => 3, 'semester' => 5],

            // Program Studi 7: Teknolofi INformasi
            ['id_mk' => 31, 'id_ps' => 7, 'nama_matkul_id' => 'Algoritma dan Pemrograman', 'nama_matkul_en' => 'Algorithms and Programming', 'matkul_desc_id' => 'Dasar-dasar logika pemrograman, penyelesaian masalah, dan implementasi algoritma.', 'matkul_desc_en' => 'Fundamentals of programming logic, problem-solving, and algorithm implementation.', 'jumlah_sks' => 3, 'semester' => 1],
            ['id_mk' => 32, 'id_ps' => 7, 'nama_matkul_id' => 'Struktur Data', 'nama_matkul_en' => 'Data Structures', 'matkul_desc_id' => 'Cara mengorganisir dan menyimpan data dalam komputer agar dapat digunakan secara efisien.', 'matkul_desc_en' => 'Ways to organize and store data in a computer so that it can be used efficiently.', 'jumlah_sks' => 3, 'semester' => 2],
            ['id_mk' => 33, 'id_ps' => 7, 'nama_matkul_id' => 'Basis Data', 'nama_matkul_en' => 'Databases', 'matkul_desc_id' => 'Konsep dan implementasi sistem untuk mengelola kumpulan data yang besar dan terstruktur.', 'matkul_desc_en' => 'Concepts and implementation of systems for managing large and structured collections of data.', 'jumlah_sks' => 3, 'semester' => 3],
            ['id_mk' => 34, 'id_ps' => 7, 'nama_matkul_id' => 'Rekayasa Perangkat Lunak', 'nama_matkul_en' => 'Software Engineering', 'matkul_desc_id' => 'Metodologi dan praktik untuk merancang, mengembangkan, dan memelihara perangkat lunak.', 'matkul_desc_en' => 'Methodologies and practices for designing, developing, and maintaining software.', 'jumlah_sks' => 3, 'semester' => 4],
            ['id_mk' => 35, 'id_ps' => 7, 'nama_matkul_id' => 'Kecerdasan Buatan', 'nama_matkul_en' => 'Artificial Intelligence', 'matkul_desc_id' => 'Studi tentang bagaimana membuat komputer dapat melakukan tugas yang memerlukan kecerdasan manusia.', 'matkul_desc_en' => 'The study of how to make computers perform tasks that require human intelligence.', 'jumlah_sks' => 3, 'semester' => 5],

            // Program Studi 8: Teknik Elektro
            ['id_mk' => 36, 'id_ps' => 8, 'nama_matkul_id' => 'Dasar-Dasar Listrik', 'nama_matkul_en' => 'Fundamentals of Electricity', 'matkul_desc_id' => 'Hukum dan konsep dasar rangkaian listrik arus searah dan bolak-balik.', 'matkul_desc_en' => 'Basic laws and concepts of direct current and alternating current electrical circuits.', 'jumlah_sks' => 3, 'semester' => 1],
            ['id_mk' => 37, 'id_ps' => 8, 'nama_matkul_id' => 'Elektronika Dasar', 'nama_matkul_en' => 'Basic Electronics', 'matkul_desc_id' => 'Mempelajari komponen elektronik seperti dioda, transistor, dan op-amp serta aplikasinya.', 'matkul_desc_en' => 'Studies electronic components such as diodes, transistors, and op-amps and their applications.', 'jumlah_sks' => 3, 'semester' => 2],
            ['id_mk' => 38, 'id_ps' => 8, 'nama_matkul_id' => 'Sistem Digital', 'nama_matkul_en' => 'Digital Systems', 'matkul_desc_id' => 'Logika digital, aljabar Boolean, dan perancangan rangkaian kombinasional dan sekuensial.', 'matkul_desc_en' => 'Digital logic, Boolean algebra, and the design of combinational and sequential circuits.', 'jumlah_sks' => 3, 'semester' => 3],
            ['id_mk' => 39, 'id_ps' => 8, 'nama_matkul_id' => 'Mikrokontroler', 'nama_matkul_en' => 'Microcontrollers', 'matkul_desc_id' => 'Arsitektur dan pemrograman perangkat mikrokontroler untuk sistem tertanam.', 'matkul_desc_en' => 'Architecture and programming of microcontroller devices for embedded systems.', 'jumlah_sks' => 2, 'semester' => 4],
            ['id_mk' => 40, 'id_ps' => 8, 'nama_matkul_id' => 'Sistem Kendali', 'nama_matkul_en' => 'Control Systems', 'matkul_desc_id' => 'Analisis dan perancangan sistem untuk mengendalikan perilaku sistem dinamis.', 'matkul_desc_en' => 'Analysis and design of systems to control the behavior of dynamic systems.', 'jumlah_sks' => 3, 'semester' => 5],

            // Program Studi 9: Teknik Geologi
            ['id_mk' => 41, 'id_ps' => 9, 'nama_matkul_id' => 'Geologi Fisik', 'nama_matkul_en' => 'Physical Geology', 'matkul_desc_id' => 'Mempelajari proses-proses fisik yang membentuk dan mengubah permukaan bumi.', 'matkul_desc_en' => 'Studies the physical processes that shape and change the Earth\'s surface.', 'jumlah_sks' => 3, 'semester' => 1],
            ['id_mk' => 42, 'id_ps' => 9, 'nama_matkul_id' => 'Mineralogi', 'nama_matkul_en' => 'Mineralogy', 'matkul_desc_id' => 'Studi tentang mineral, termasuk identifikasi, kristalografi, dan sifat fisiknya.', 'matkul_desc_en' => 'The study of minerals, including their identification, crystallography, and physical properties.', 'jumlah_sks' => 3, 'semester' => 2],
            ['id_mk' => 43, 'id_ps' => 9, 'nama_matkul_id' => 'Petrologi', 'nama_matkul_en' => 'Petrology', 'matkul_desc_id' => 'Studi tentang asal-usul, komposisi, dan klasifikasi batuan.', 'matkul_desc_en' => 'The study of the origin, composition, and classification of rocks.', 'jumlah_sks' => 3, 'semester' => 3],
            ['id_mk' => 44, 'id_ps' => 9, 'nama_matkul_id' => 'Struktur Geologi', 'nama_matkul_en' => 'Structural Geology', 'matkul_desc_id' => 'Analisis deformasi batuan dan struktur geologi seperti lipatan dan sesar.', 'matkul_desc_en' => 'Analysis of rock deformation and geological structures such as folds and faults.', 'jumlah_sks' => 2, 'semester' => 4],
            ['id_mk' => 45, 'id_ps' => 9, 'nama_matkul_id' => 'Geologi Teknik', 'nama_matkul_en' => 'Engineering Geology', 'matkul_desc_id' => 'Penerapan prinsip geologi dalam praktik rekayasa, khususnya untuk proyek konstruksi.', 'matkul_desc_en' => 'Application of geological principles in engineering practice, especially for construction projects.', 'jumlah_sks' => 3, 'semester' => 5],
        ]);
    }
}
